### ISSUE TITLE
Sender address rejected: Domain not found

### ISSUE THREAD

**Issue by changloong** [hardware/mailserver#1]
the error message from gmail when I try sent mail from gmail to mailserver:

```sh
450 4.1.8 <xxxxxx@gmail.com>: Sender address rejected: Domain not found
```

**Comment by changloong** [comment]
the problem is because I can not use dns from container, I try add net:host then it will start for me.

```sh
docker-compose.sh up -d
mailserver_mariadb_1 is up-to-date
Creating mailserver_mail_1
ERROR: Conflicting options: -h and the network mode (--net)
```

**Comment by hardware** [comment]
If you only use network mode (--net), it should work with host's networking stack without hostname option (-h), that means the host server's FQDN is configured properly. What are you trying to do exactly ? Put the content of your docker-compose.yml please.

**Comment by changloong** [comment]
I just want to make the container can receive email, it can not receive or sent email by default settings.  

Here is the error message from gmail:

```conf
This is an automatically generated Delivery Status Notification

THIS IS A WARNING MESSAGE ONLY.

YOU DO NOT NEED TO RESEND YOUR MESSAGE.

Delivery to the following recipient has been delayed:

     admin@gmcstatic.com

Message will be retried for 2 more day(s)

Technical details of temporary failure:
Google tried to deliver your message, but it was rejected by the server for the recipient domain gmcstatic.com by mail.gmcstatic.com. [139.162.158.66].

The error that the other server returned was:
450 4.1.8 <xxxxxxxx@gmail.com>: Sender address rejected: Domain not found


----- Original message -----

DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=gmail.com; s=20120113;
        h=mime-version:in-reply-to:references:date:message-id:subject:from:to
         :content-type;
        bh=PfEfpq20Y5MXmUBWW0iFCXvykUoOzMBufwI/vMhYL+o=;
        b=RLgUa8Q3oaiNQOzmGYTs8tgfEYFFLTt1ktSM4aaqTYwBP4pVo7+DsR3/zJPQ0Rn8ur
         fGLg5iuHDlEOVpY5NjqiYew3OxSkIdSXZc0oRK8FdB8LqkSxfO/zwmRZuePKMV0uxiiY
         Js58JRh3gnygmuZIFX8m6uhzdxXEnmANMAOWg3m/HM2AaE6nANEng2UhjBdHeMwNa8n6
         ApmhYKeLMqmo0MngE8y2x0Eomlc+9GFKmtJGY9z4lvoM5SbSFi1qTXzcobl/q6zkMwFT
         AeMNI8c/xm8WtdZ1hUvxk7GamFXSvcg/6BCZngMDsdmfZJT4nM6hKdW1sVlYapYEWtxH
         L73Q==
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20130820;
        h=x-gm-message-state:mime-version:in-reply-to:references:date
         :message-id:subject:from:to:content-type;
        bh=PfEfpq20Y5MXmUBWW0iFCXvykUoOzMBufwI/vMhYL+o=;
        b=eeMOVoKnUHS92mgzD7G0kWj1khsZmJpBbdb+mVFuEDuk5gUrTeJb519CzzEj+otFBa
         oIXRC1QcmY+eGD+doGuvQ278jp2ttjNZphPEH07KoTyyl2hqBf8w0vjU0nVELA5haaks
         lkxI3WCZmYyRt+aJu4n11IDrUl5wvKOsVspym5WNejWW1GSPh++ynr6trJV2X7JG8gE5
         hSpsMycCU7adqKveQYm50hr7I47fb1jbrfyGF0AtpXUCepP584hVkg7Ne/R/M239LhtJ
         gJnlKGKuO850lSXsp3WNtJIl4tdn2wyeuD7nF1egC2bcNsaOgp1oVuKqVPr2ujub5nNM
         jC6A==
X-Gm-Message-State: AG10YOS6S++Okm/hl0kS927oWZ9fJULc6tvl410SwrkJ5dJ6DLd6l66zRERBRJivAlTVULZNLZmc/SMYXNsIdw==
MIME-Version: 1.0
X-Received: by 10.107.161.206 with SMTP id k197mr12660249ioe.139.1453637566362;
 Sun, 24 Jan 2016 04:12:46 -0800 (PST)
Received: by 10.36.48.145 with HTTP; Sun, 24 Jan 2016 04:12:46 -0800 (PST)
In-Reply-To: <CACS0EghUgPgv3HcrZWVHcH7Yohd=N4rR3Fq6KDTKhf0N=mre5Q@mail.gmail.com>
References: <CACS0EghUgPgv3HcrZWVHcH7Yohd=N4rR3Fq6KDTKhf0N=mre5Q@mail.gmail.com>
Date: Sun, 24 Jan 2016 20:12:46 +0800
Message-ID: <CACS0EgjA4Ftu5WkR79dUo+zW6_sPUuR5kW9r2H0K-_QYMf39=w@mail.gmail.com>
Subject: Re: test haha
From: Long Chang <xxxxx@gmail.com>
To: admin@gmcstatic.com
Content-Type: multipart/alternative; boundary=001a1140f988c67a56052a135e27
```

**Comment by changloong** [comment]
here you go: 
```yml
mail:
  image: hardware/mailserver
  domainname: gmcstatic.com
  hostname: mail
  dns:
    - 172.17.0.1
  links:
    - mariadb:mariadb
  ports:
    - "25:25"
    - "143:143"
    - "465:465"
    - "587:587"
    - "993:993"
    - "4190:4190"
    - "8388:8388"
  environment:
    - DBHOST=mariadb
    - DBUSER=postfix
    - DBNAME=postfix
    - DBPASS=password
  volumes:
    - /root/docker-composes/root:/root
    - /etc/letsencrypt:/etc/letsencrypt
    - /opt/docker/mail:/var/mail
    - /opt/docker/dovecot:/var/lib/dovecot
    - /opt/docker/opendkim:/etc/opendkim/keys

mariadb:
  image: mariadb:10.1
  ports:
    - "3306:3306"
  volumes:
    - /opt/docker/mysql/db:/var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_DATABASE=postfix
    - MYSQL_USER=postfix
    - MYSQL_PASSWORD=password
```
I can make it start without domain name and use net:host option,  but this will also make container less safety.

I try add the option: default-gateway: 172.17.0.1,  with `iptables -t nat -A POSTROUTING -s 172.17.0.0/16  -j MASQUERADE` on host. it run into this error:

```sh
ERROR: Validation failed in file './docker-compose.yml', reason(s):
Unsupported config option for 'mail' service: 'default-gateway'
```
