### ISSUE TITLE
smtp not working

### ISSUE THREAD

**Issue by Doniz** [hardware/mailserver#106]
Hello, thanks for an awesome repository. I was using this repo actually couple times with different servers. But first time when i was using, i installed server on the same server as the web are.

Now i have a 2 servers, one for web and second one for mail server only with different ip address.

so i'm trying setup mail.example.com with docker-compose file as it mention in the README.md,

```yaml
mailserver:
    image: hardware/mailserver
    container_name: mailserver
    domainname: example.com
    hostname: mail
    restart: always
```

so as i understand `domainname` should be only a first level domain `example.com`. 

so i finish setup but,

![](http://i64.tinypic.com/2pzlbon.png)

SMTP server not running on the sub-domain. How can i debug or see the problems why? 

btw domain settings:

```
example.com A XX.XX.XX.X1
mail.example.com A XX.XX.XX.X2

example.com MX 10 mail.example.com

example.com TXT "v=spf1 a mx ip4:XX.XX.XX.X2 ~all"
```

i'm not using `NSD` for domains. Have different domain provider. If i try https://mxtoolbox.com/SuperTool.aspx?action=smtp to test SMTP, i type mail.example.com in the text field, and i get success results:

```
220 mail.example.com ESMTP Postfix

SMTP Reverse DNS Mismatch	OK - 51.15.59.42 resolves to mail.taskinn.com
SMTP Valid Hostname		OK - Reverse DNS is a valid Hostname
SMTP Banner Check		OK - Reverse DNS matches SMTP Banner
SMTP TLS			OK - Supports TLS.
SMTP Connection Time		0.859 seconds - Good on Connection time
SMTP Open Relay			OK - Not an open relay.
SMTP Transaction Time		3.125 seconds - Good on Transaction Time

```

```
Connecting to XX.XX.XX.X2

220 mail.example.com ESMTP Postfix [672 ms]
EHLO PWS3.mxtoolbox.com
250-mail.example.com
250-PIPELINING
250-SIZE 502400000
250-ETRN
250-STARTTLS
250-ENHANCEDSTATUSCODES
250-8BITMIME
250 DSN [719 ms]
MAIL FROM:<supertool@mxtoolbox.com>
250 2.1.0 Ok [719 ms]
RCPT TO:<test@example.com>
554 5.7.1 <test@example.com>: Relay access denied [719 ms]

PWS3v2 4422ms
```

Regards, Donatas

**Comment by hardware** [comment]
What was the problem ?

**Comment by Doniz** [comment]
SMTP ports was blocking by the server. Half of day was waste of time.

**Comment by Doniz** [comment]
to check if the ports are not blocking, run this helpful command:

`netstat -tulpn | grep -E -w '25|80|110|143|443|465|587|993|995'`

**Comment by pepya2** [comment]
@Doniz how did you fix.. i am getting the same error.. 
`netstat -tulpn | grep -E -w '25|80|110|143|443|465|587|993|995'` have all ports open..
![ph](https://user-images.githubusercontent.com/25289859/44659521-2d883c80-aa0d-11e8-91a4-2389d9a8f605.png)

result from mxtoolbox.com
```
Connecting to IPADRESS

220 mail.takeer.com ESMTP Postfix [1314 ms]
EHLO EC2AMAZ-14J9QQI.mxtoolbox.com
250-mail.domain.com
250-PIPELINING
250-SIZE 502400000
250-ETRN
250-STARTTLS
250-ENHANCEDSTATUSCODES
250-8BITMIME
250-DSN
250 SMTPUTF8 [642 ms]
MAIL FROM:<supertool@mxtoolbox.com>
250 2.1.0 Ok [687 ms]
RCPT TO:<test@mxtoolboxsmtpdiag.com>
554 5.7.1 <test@mxtoolboxsmtpdiag.com>: Relay access denied [673 ms]

LookupServerv2 3676ms
```
Thank you.

**Comment by navossoc** [comment]
@pepya2 You need to fill the `Server` field with the public ip or dns where your `mailserver` container is running.

**Comment by pepya2** [comment]
@navossoc in mxtoolbox.com yes i added public ip of my server..

**Comment by navossoc** [comment]
What is exactly your problem? You can't send emails to outside?
Did you set up rainloop? are you able to receive and read messages there?

[]'s

**Comment by pepya2** [comment]
i am receiving email fine, even sending mails via rainloop works without errors.. issue is sending mail from other containers via smtp.. it can't connect
`ssmtp: Cannot open mail.domain.com:587`
ports are open..
configuration is the same as instruction..

**Comment by pepya2** [comment]
i have tried even setting /etc/ssmtp/ permission to 777.. thinking maybe it is a permission error to read ssmtp.conf file.. but still the same error..

**Comment by navossoc** [comment]
Maybe it be an issue with STARTTLS on :587.
You should try another ports like :25 or :465 (TLS) first, just to be sure.

Also, if you are running `ssmtp` inside a container on the same machine as the `mailserver`, you can connect to it by simple using the `mailserver` hostname.

**Comment by pepya2** [comment]
okay @navossoc  let me try..

**Comment by pepya2** [comment]
I am using `ssmtp` inside a container on the same machine **YES**, so i changed to `mailserver,` still `ssmtp: Cannot open mailserver.....`
added another container for testing.. dumped PHPMailer.. in Host i used `'mailserver'`, `port 587 tls`, still gave this nice message..
`SMTP Error: Could not connect to SMTP host.`
Main issue that i don't understand, why Rainloop works fine, i can send mails without issue.. using another container that has my app and needs to send emails when user registered is an issue.. connection fail.. while ports are open..

**Comment by navossoc** [comment]
Ok, I think I know your issue now.

How are you running this another container? command line or docker-compose?

Did you put it on the same network?
```docker run .... --network mail_network```

```
    # ...
    networks:
      - mail_network
```

**Comment by pepya2** [comment]
Sure.. on the same network.. i only have internal and proxy
this is mailserver docker-compose entry..
  # MAIL SERVER
```
  mailserver:
    image: hardware/mailserver:${MAILSERVER_DOCKER_TAG}
    container_name: mailserver
    restart: ${RESTART_MODE}
    domainname: ${MAIN_DOMAIN}                    # Mail server A/MX/FQDN & reverse PTR = mail.domain.tld.
    hostname: ${MAIN_HOSTNAME}
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:spam.${MAIN_DOMAIN}
      - traefik.port=11334
      - traefik.docker.network=proxy
    # extra_hosts:                          - Required for external database (on other server or for local databases on host without docker)
    #  - "mariadb:xx.xx.xx.xx"              - Replace with IP address of MariaDB server
    #  - "redis:xx.xx.xx.xx"                - Replace with IP address of Redis server
    ports:
      - "25:25"       # SMTP                - Required
      - "110:110"     # POP3       STARTTLS - Optional - For webmails/desktop clients
      - "143:143"     # IMAP       STARTTLS - Optional - For webmails/desktop clients
      - "465:465"     # SMTPS      SSL/TLS  - Optional - Enabled for compatibility reason, otherwise disabled
      - "587:587"     # Submission STARTTLS - Optional - For webmails/desktop clients
      - "993:993"     # IMAPS      SSL/TLS  - Optional - For webmails/desktop clients
    # - "995:995"     # POP3S      SSL/TLS  - Optional - For webmails/desktop clients
      - "4190:4190"   # SIEVE      STARTTLS - Optional - Recommended for mail filtering
    environment:
      - DBPASS=${DATABASE_USER_PASSWORD}       # MariaDB database password (required)
      - RSPAMD_PASSWORD=${RSPAMD_PASSWORD}     # Rspamd WebUI password (required)
      - ADD_DOMAINS=domain.com      # Add additional domains separated by commas (needed for dkim keys etc.)
    # - DEBUG_MODE=true                        # Enable Postfix, Dovecot and Rspamd verbose logging
      - ENABLE_POP3=true                       # Enable POP3 protocol
    # - ENABLE_FETCHMAIL=true                  # Enable fetchmail forwarding
    # - DISABLE_CLAMAV=true                    # Disable virus scanning
    # - DISABLE_SIGNING=true                   # Disable DKIM/ARC signing
      - RELAY_NETWORKS=192.168.0.0/16 172.16.0.0/12 10.0.0.0/8
      - DISABLE_GREYLISTING=true               # Disable greylisting policy
      - DISABLE_RATELIMITING=true              # Disable ratelimiting policy
    #
    # Full list : https://github.com/hardware/mailserver#environment-variables
    #
    volumes:
      - ${VOLUMES_ROOT_PATH}/mail:/var/mail
      - ${VOLUMES_ROOT_PATH}/traefik/acme:/etc/letsencrypt/acme
    depends_on:
      - mariadb
      - redis
    networks:
      - internal
      - proxy

 # EMAIL TESTING..
  email:
    image: pepya2/phpapache:latest
    container_name: "email"
    restart: ${RESTART_MODE}
    environment:
      - ALLOW_OVERRIDE=true
    volumes:
      - ${VOLUMES_ROOT_PATH}/data/test:/var/www/html
    labels:
      - "traefik.backend=email"
      - "traefik.frontend.rule=Host:test.domain.com"
      - "traefik.docker.network=proxy"
      - "traefik.frontend.passHostHeader=true"
    networks:
      - internal
      - proxy
```

I tried to check on TLS as you said maybe have issue.. gave me this result..

```
Trying TLS on mail.domain.com[XX.XX.XX.XX] (0):

seconds		test stage and result
[000.049]		Connected to server
[000.525]	<-- 	220 mail.domain.com ESMTP Postfix
[000.532]		We are allowed to connect
[000.536]	 -->	EHLO www6.CheckTLS.com
[000.586]	<-- 	250-mail.domain.com
250-PIPELINING
250-SIZE 502400000
250-ETRN
250-STARTTLS
250-ENHANCEDSTATUSCODES
250-8BITMIME
250-DSN
250 SMTPUTF8
[000.588]		We can use this server
[000.588]		TLS is an option on this server
[000.589]	 -->	STARTTLS
[000.652]	<-- 	220 2.0.0 Ready to start TLS
[000.653]		STARTTLS command works on this server
[000.937]		Connection converted to SSL
SSLVersion in use: TLSv1_2
Cipher in use: ECDHE-RSA-AES256-GCM-SHA384
Certificate 1 of 3 in chain: Cert VALIDATED: ok
Cert Hostname VERIFIED (mail.domain.com = *.domain.com | DNS:*.domain.com)
cert not revoked by CRL
cert not revoked by OCSP
serialNumber=03:06:bf:3a:ab:38:f4:a2:f2:f7:ad:97:0e:22:12:cd:72:47
subject= /CN=*.domain.com
issuer= /C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
Certificate 2 of 3 in chain: Cert VALIDATED: ok
cert not revoked by CRL
cert not revoked by OCSP
serialNumber=0a:01:41:42:00:00:01:53:85:73:6a:0b:85:ec:a7:08
subject= /C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
issuer= /O=Digital Signature Trust Co./CN=DST Root CA X3
Certificate 3 of 3 in chain: Cert VALIDATED: ok
cert not revoked by CRL
cert not revoked by OCSP
serialNumber=44:af:b0:80:d6:a3:27:ba:89:30:39:86:2e:f8:40:6b
subject= /O=Digital Signature Trust Co./CN=DST Root CA X3
issuer= /O=Digital Signature Trust Co./CN=DST Root CA X3
[001.626]	 ~~>	EHLO www6.CheckTLS.com
[001.675]	<~~ 	250-mail.domain.com
250-PIPELINING
250-SIZE 502400000
250-ETRN
250-AUTH PLAIN LOGIN
250-AUTH=PLAIN LOGIN
250-ENHANCEDSTATUSCODES
250-8BITMIME
250-DSN
250 SMTPUTF8
[001.679]		TLS successfully started on this server
[001.680]	 ~~>	MAIL FROM:<test@checktls.com>
[001.788]	<~~ 	250 2.1.0 Ok
[001.793]		Sender is OK
[001.795]	 ~~>	QUIT
[001.852]	<~~ 	221 2.0.0 Bye
```
