### ISSUE TITLE
DKIM for second domain

### ISSUE THREAD

**Issue by nmahadkar** [hardware/mailserver#121]
How I get emails for a second domain signed by DKIM?

**Comment by hardware** [comment]
With `ADD_DOMAINS` env variable.

```yml
mailserver:
    image: hardware/mailserver
    domainname: domain.tld
    hostname: mail
    environment:
      - ADD_DOMAINS=mail.other-domain.tld,mail.super-domain.tld
    ...
```
