### ISSUE TITLE
[mailserver-rainloop]

### ISSUE THREAD

**Issue by Rathorian** [hardware/mailserver#128]
Salut,

J'avais des soucis concernant l'heure affiché dans PostfixAdmin et Rainloop.
J'ai fais des modifications à la main sur mes conteneurs mais ça pourrait être plus sympa d'avoir les modifications de base sur les CT's à moins qu'il y est plus simple...

Pourrais-tu ajouter à l'image "Rainloop" dans le fichier "php-fpm.conf" : 

`php_admin_value[date.timezone] = Europe/Paris`

Et dans l'image "mailserver" dans le fichier "docker-compose.sample.yml" : 
```
  mariadb:
    image: mariadb:10.1
    container_name: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=XXXXXXXXXXXXXXXXXXXXXXXXXXX
      - MYSQL_DATABASE=postfix
      - MYSQL_USER=postfix
      - MYSQL_PASSWORD=XXXXXXXXXXXXXXXXXXXXXXXXXXX
      **- TZ=Europe/Paris**
    volumes:
      - /mnt/docker/mysql/db:/var/lib/mysql
```
Merci
