### ISSUE TITLE
rspamd as container

### ISSUE THREAD

**Issue by AnthoDingo** [hardware/mailserver#163]
Hello,

Is there any way to export rspamd to container and link mailserver to it ?
Ideas is to centralized rspamd.

I don't know if it's possible.

**Comment by denji** [comment]
* https://rspamd.com/doc/workers/rspamd_proxy.html#proxy-mode
![rspamd_milter_proxy](https://user-images.githubusercontent.com/3759759/30287282-247e90e2-972d-11e7-885b-27796acb649a.png)

**Comment by hardware** [comment]
```yml
mailserver:
  # extra_hosts:     # Required if your rspamd instance isn't on the same server
  #  - "rspamd-container:xx.xx.xx.xx"
  volumes:
    - /path/to/worker-proxy.inc:/etc/rspamd/local.d/worker-proxy.inc:ro
```

```inc
# worker-proxy.inc

bind_socket = "*:11332";
milter = yes;
timeout = 120s;

upstream "scan" {
  default = yes;
  hosts = "rspamd-container:11333";
  key = "..."; # Public key for encryption, generated by rspamadm keypair (optional)
  compression = yes; 
}
```

```
rspamadm keypair --help
```

https://rspamd.com/doc/workers/rspamd_proxy.html#proxy-mode
https://rspamd.com/doc/configuration/upstream.html
https://rspamd.com/doc/rspamadm.html
