### ISSUE TITLE
[Question] How can I add a domain to whitelist? 

### ISSUE THREAD

**Issue by sknight80** [hardware/mailserver#190]
Hi Team,

I was wondering, how I can add a domain to the whitelist so the rspam filter can bypass?
Is this a setting in RSPAMD web interface?

Thank you,
Istvan

**Comment by hardware** [comment]
You can setup something like this :

```ini
# /etc/rspamd/local.d/whitelist.conf

"WHITELIST_CUSTOM_DOMAIN" = {
    valid_spf = true;
    valid_dkim = true;
    # or just 
    # valid_dmarc = true;
    domains = [
        "domain.tld",
    ];
    description = "Mail comes from the whitelisted domain and has valid SPF and DKIM policies";
    score = -5.0
}
```

```yml
mailserver:
  volumes:
    - /path/to/custom/whitelist.conf:/etc/rspamd/local.d/whitelist.conf
```

https://www.rspamd.com/doc/modules/whitelist.html
