### ISSUE TITLE
[Traefik] SSL certificates generation error

### ISSUE THREAD

**Issue by Rathorian** [hardware/mailserver#215]
#### Classification

* [X] Question

#### Reproducibility

* [x] Always

#### Docker information
```
docker info

Containers: 7
 Running: 7
 Paused: 0
 Stopped: 0
Images: 7
Server Version: 17.12.0-ce
Storage Driver: btrfs
 Build Version: Btrfs v4.7.3
 Library Version: 101
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.0-5-amd64
Operating System: Debian GNU/Linux 9 (stretch)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.941GiB
Name: ns1
ID: ELQG:C65J:7JF2:2SLS:DEP6:VODZ:Y4OB:SEOB:KRWF:6ZP4:2ETL:GONB
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

docker images hardware/mailserver --digests --filter "dangling=false"

hardware/mailserver   1.1-stable          sha256:4f4c4dd1c7ebd0a42c60b599155c797fca29d37dfb6f7e5e1d75479d36b999fe   6b7c4c8eacd4        27 hours ago        333MB
```

#### Description
Après avoir tout mis en place correctement les fichiers (docker-compose.yml, .env, acme.json, traefik.toml) je lance la commande "docker-compose up -d" puis quand je regarde les logs de "mailserver" il ne génère pas les certificats.

#### Debugging information
```
docker logs mailserver

[INFO] Search for SSL certificates generated by Traefik
[INFO] ...
[INFO] ...
[INFO] ...
[INFO] ...
[INFO] ...
[INFO] ...
[INFO] ...
[INFO] ...
[INFO] ...
[INFO] acme.json found, dumping into pem files
[ERROR] mail.domaine.fr.crt or mail.domaine.fr.key not found !
[INFO] Don't forget to add a new traefik frontend rule to generate a certificate for mail.domaine.fr subdomain
[INFO] Look /mnt/docker/traefik/acme/dump.log for more information
[INFO] Search for SSL certificates generated by Traefik
[INFO] acme.json found, dumping into pem files
[ERROR] mail.domaine.fr.crt or mail.domaine.fr.key not found !
[INFO] Don't forget to add a new traefik frontend rule to generate a certificate for mail.domaine.fr subdomain
[INFO] Look /mnt/docker/traefik/acme/dump.log for more information
```

```
traefik/acme/dump.log

writing RSA key
writing RSA key
writing RSA key
writing RSA key
writing RSA key
writing RSA key
writing RSA key
writing RSA key
writing RSA key

```

```
traefik/acme/acme.json

{
  "Email": "contact@domaine.fr",
  "Registration": {
    "body": {
      "resource": "reg",
      "id": 29674525,
      "key": {
        "kty": "RSA",
        "n": "tLzDF1gq27wXhoI0QFjboSfNKmKcVfboNrM1OHdE5SvWWX96WGsl-9wdb8ttcR4EgztOwrzx7O5JaOAgfMecSPHe8agdHacEoPAlzcTdj1kEeA0H5GUlM6AInS6blW3wAe3dwypwnvl9j48OKArfZCQmPmZqSOtTb4WICCeFR4rmCItDCDjS-xaz78BQFNlLaowcZ88n0WfhbttIqNbYPVjGvlLTY6$
        "e": "AQAB"
      },
      "contact": [
        "mailto:contact@domaine.fr"
      ],
      "agreement": "https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf"
    },
    "uri": "https://acme-v01.api.letsencrypt.org/acme/reg/29674525",
    "new_authzr_uri": "https://acme-v01.api.letsencrypt.org/acme/new-authz",
    "terms_of_service": "https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf"
  },
  "PrivateKey": "...",
  "DomainsCertificate": {
    "Certs": []
  },
  "ChallengeCerts": {},
  "HTTPChallenge": {}
}
```

#### Configuration (docker-compose.yml, traefik.toml...etc)

```
docker-compose.yml

version: '3.5'

networks:
  http_network:
    external: true
  mail_network:
    external: false

services:
  traefik:
    image: traefik:1.5-alpine
    container_name: traefik
    restart: ${RESTART_MODE}
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:mail.${DOMAIN}
      - traefik.backend.port=8080
      - traefik.docker.network=http_network
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${VOLUMES_ROOT_PATH}/traefik/traefik.toml:/traefik.toml:ro
      - ${VOLUMES_ROOT_PATH}/traefik/acme:/etc/traefik/acme
    networks:
      - http_network

  mailserver:
    image: hardware/mailserver:${MAILSERVER_DOCKER_TAG}
    container_name: mailserver
    restart: ${RESTART_MODE}
    domainname: ${DOMAIN}
    hostname: ${HOSTNAME}
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:spam.${DOMAIN}
      - traefik.backend.port=11334
      - traefik.docker.network=http_network
    ports:
      - "25:25"     # SMTP
      - "143:143"   # IMAP       STARTTLS
      - "587:587"   # Submission STARTTLS
      - "993:993"   # IMAPS      SSL/TLS
      - "4190:4190" # SIEVE      STARTTLS
    environment:
      - VMAILUID=1000
      - VMAILGID=1000
      - DBHOST=postfix-db
      - DBPASS=${DATABASE_USER_PASSWORD}
      - REDIS_HOST=redis-mailserver
      - RSPAMD_PASSWORD=${RSPAMD_PASSWORD}
      - ADD_DOMAINS=second-domaine.fr
    volumes:
      - ${VOLUMES_ROOT_PATH}/mail:/var/mail
      - ${VOLUMES_ROOT_PATH}/traefik/acme:/etc/letsencrypt/acme
    depends_on:
      - postfix-db
      - redis-mailserver
    networks:
      - mail_network
      - http_network

  postfixadmin:
    image: hardware/postfixadmin
    container_name: postfixadmin
    restart: ${RESTART_MODE}
    domainname: ${DOMAIN}
    hostname: ${HOSTNAME}
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:postfixadmin.${DOMAIN}
      - traefik.backend.port=8888
      - traefik.docker.network=http_network
    environment:
      - UID=1000
      - GID=1000
      - DBHOST=postfix-db
      - DBPASS=${DATABASE_USER_PASSWORD}
    depends_on:
      - mailserver
      - postfix-db
    networks:
      - mail_network
      - http_network

  rainloop:
    image: hardware/rainloop
    container_name: rainloop
    restart: ${RESTART_MODE}
    labels:
      - traefik.enable=true
      - traefik.backend.port=8888
      - traefik.frontend.rule=Host:webmail.${DOMAIN}
      - traefik.docker.network=http_network
    environment:
      - UID=1000
      - GID=1000
    volumes:
      - ${VOLUMES_ROOT_PATH}/rainloop:/rainloop/data
    depends_on:
      - mailserver
      - postfix-db
    networks:
      - mail_network
      - http_network

  postfix-db:
    image: mariadb:10.2
    container_name: postfix-db
    restart: ${RESTART_MODE}
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
      - MYSQL_DATABASE=postfix
      - MYSQL_USER=postfix
      - MYSQL_PASSWORD=${DATABASE_USER_PASSWORD}
    volumes:
      - ${VOLUMES_ROOT_PATH}/postfix-db:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    networks:
      - mail_network

  redis-mailserver:
    image: redis:4.0-alpine
    container_name: redis-mailserver
    restart: ${RESTART_MODE}
    command: redis-server --appendonly yes
    volumes:
      - ${VOLUMES_ROOT_PATH}/redis-mailserver:/data
    networks:
      - mail_network

  nsd:
    image: hardware/nsd-dnssec
    container_name: nsd
    restart: ${RESTART_MODE}
    environment:
      - UID=1000
      - GID=1000
    ports:
      - "53:53"
      - "53:53/udp"
    volumes:
      - ${VOLUMES_ROOT_PATH}/nsd/conf:/etc/nsd
      - ${VOLUMES_ROOT_PATH}/nsd/zones:/zones
      - ${VOLUMES_ROOT_PATH}/nsd/db:/var/db/nsd
```

```
traefik.toml

defaultEntryPoints = ["https","http"]

[api]
entryPoint = "traefik"
dashboard = true

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
    minVersion = "VersionTLS12"
    cipherSuites = ["TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384", "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305"]
  [entryPoints.traefik]
  address = ":8080"
  [entryPoints.traefik.auth.basic]
  users = ["Admin:$2y$10$lSc756dfq4dfqfdfqsbvAiYM4/PJdfhs56468sdgf4687fdqsg"]

[acme]
email = "contact@domaine.fr"
storage = "/etc/traefik/acme/acme.json"
entryPoint = "https"
onHostRule = true
onDemand = false
  [acme.httpChallenge]
  entryPoint = "http"

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "domaine.fr"
watch = true
exposedbydefault = false
```

**Comment by hardware** [comment]
```json
"DomainsCertificate": {
    "Certs": []
}
```

You have no [domain certificate](https://github.com/hardware/mailserver/blob/538c11f5599b993225abc4029c7d178efb26814c/test/share/traefik/acme.json) in your acme.json file. Are you sure that traefik acquired them ? Do you have any errors in Traefik logs ?

Turn on Lego logging :
```toml
[acme]
acmeLogging = true
```
```
docker logs -f traefik
```

**Comment by Rathorian** [comment]
Yes, I saw that the file "traefik.toml" had no certificate, yet everything is configured as in your documentation.

I added suddenly the logs for acme, here is his return:
```
docker logs -f traefik


legolog: 2018/02/18 14:41:27 [INFO] acme: Registering account for contact@domaine.fr
time="2018-02-18T14:41:29Z" level=error msg="Error creating server: http2: TLSConfig.CipherSuites is missing HTTP/2-required TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
legolog: 2018/02/18 14:41:29 [INFO][spam.domaine.fr] acme: Obtaining bundled SAN certificate
legolog: 2018/02/18 14:41:29 [INFO][spam.domaine.fr] AuthURL: https://acme-v01.api.letsencrypt.org/acme/authz/whDGUh0z17PaIc3ZDXuAKA_TPQ1gmLcxXOd2-ec_i2k
legolog: 2018/02/18 14:41:29 [INFO][spam.domaine.fr] acme: Could not find solver for: dns-01
legolog: 2018/02/18 14:41:29 [INFO][spam.domaine.fr] acme: Trying to solve HTTP-01
legolog: 2018/02/18 14:41:31 [INFO][spam.domaine.fr] The server validated our request
legolog: 2018/02/18 14:41:31 [INFO][spam.domaine.fr] acme: Validations succeeded; requesting certificates
time="2018-02-18T14:42:08Z" level=error msg="map[spam.domaine.fr:acme: Error 429 - urn:acme:error:rateLimited - Error creating new cert :: too many certificates already issued for exact set of domains: spam.domaine.fr: see https://letsencrypt.org/docs/rate-limits/]"
time="2018-02-18T14:42:08Z" level=error msg="Error getting ACME certificates [spam.domaine.fr] : cannot obtain certificates map[spam.domaine.fr:acme: Error 429 - urn:acme:error:rateLimited - Error creating new cert :: too many certificates already issued for exact set of domains: spam.domaine.fr: see https://letsencrypt.org/docs/rate-limits/]"
legolog: 2018/02/18 14:42:08 [INFO][webmail.domaine.fr] acme: Obtaining bundled SAN certificate
legolog: 2018/02/18 14:42:09 [INFO][webmail.domaine.fr] AuthURL: https://acme-v01.api.letsencrypt.org/acme/authz/cuFQjVXyQwog9zKnrfRViyau8IqpZP6gfZk9ofvC8kQ
legolog: 2018/02/18 14:42:09 [INFO][webmail.domaine.fr] acme: Could not find solver for: dns-01
legolog: 2018/02/18 14:42:09 [INFO][webmail.domaine.fr] acme: Trying to solve HTTP-01
legolog: 2018/02/18 14:42:11 [INFO][webmail.domaine.fr] The server validated our request
legolog: 2018/02/18 14:42:11 [INFO][webmail.domaine.fr] acme: Validations succeeded; requesting certificates
time="2018-02-18T14:43:30Z" level=error msg="map[webmail.domaine.fr:acme: Error 429 - urn:acme:error:rateLimited - Error creating new cert :: too many certificates already issued for exact set of domains: webmail.domaine.fr: see https://letsencrypt.org/docs/rate-limits/]"
time="2018-02-18T14:43:30Z" level=error msg="Error getting ACME certificates [webmail.domaine.fr] : cannot obtain certificates map[webmail.domaine.fr:acme: Error 429 - urn:acme:error:rateLimited - Error creating new cert :: too many certificates already issued for exact set of domains: webmail.domaine.fr: see https://letsencrypt.org/docs/rate-limits/]"
legolog: 2018/02/18 14:43:30 [INFO][mail.domaine.fr] acme: Obtaining bundled SAN certificate
legolog: 2018/02/18 14:43:31 [INFO][mail.domaine.fr] AuthURL: https://acme-v01.api.letsencrypt.org/acme/authz/_TXFsxbRAxQR1r3bNb9rmh-thH2VvO4MGWRX-eaNbQ8
legolog: 2018/02/18 14:43:31 [INFO][mail.domaine.fr] acme: Trying to solve HTTP-01
legolog: 2018/02/18 14:43:33 [INFO][mail.domaine.fr] The server validated our request
legolog: 2018/02/18 14:43:33 [INFO][mail.domaine.fr] acme: Validations succeeded; requesting certificates
time="2018-02-18T14:44:47Z" level=error msg="map[mail.domaine.fr:acme: Error 429 - urn:acme:error:rateLimited - Error creating new cert :: too many certificates already issued for exact set of domains: mail.domaine.fr: see https://letsencrypt.org/docs/rate-limits/]"
time="2018-02-18T14:44:47Z" level=error msg="Error getting ACME certificates [mail.domaine.fr] : cannot obtain certificates map[mail.domaine.fr:acme: Error 429 - urn:acme:error:rateLimited - Error creating new cert :: too many certificates already issued for exact set of domains: mail.domaine.fr: see https://letsencrypt.org/docs/rate-limits/]"
legolog: 2018/02/18 14:44:47 [INFO][postfixadmin.domaine.fr] acme: Obtaining bundled SAN certificate
legolog: 2018/02/18 14:44:48 [INFO][postfixadmin.domaine.fr] AuthURL: https://acme-v01.api.letsencrypt.org/acme/authz/YllFODsixYxcb_ISukYNgbtNeY4NrqBHnNxHfDodFsY
legolog: 2018/02/18 14:44:48 [INFO][postfixadmin.domaine.fr] acme: Trying to solve HTTP-01
legolog: 2018/02/18 14:44:49 [INFO][postfixadmin.domaine.fr] The server validated our request
legolog: 2018/02/18 14:44:49 [INFO][postfixadmin.domaine.fr] acme: Validations succeeded; requesting certificates
time="2018-02-18T14:45:23Z" level=error msg="map[postfixadmin.domaine.fr:acme: Error 429 - urn:acme:error:rateLimited - Error creating new cert :: too many certificates already issued for exact set of domains: postfixadmin.domaine.fr: see https://letsencrypt.org/docs/rate-limits/]"
time="2018-02-18T14:45:23Z" level=error msg="Error getting ACME certificates [postfixadmin.domaine.fr] : cannot obtain certificates map[postfixadmin.domaine.fr:acme: Error 429 - urn:acme:error:rateLimited - Error creating new cert :: too many certificates already issued for exact set of domains: postfixadmin.domaine.fr: see https://letsencrypt.org/docs/rate-limits/]"
```

**Comment by denji** [comment]
> Error 429 - urn:acme:error:rateLimited - Error creating new cert :: too many certificates already issued for exact set of domains

RateLimit, maybe many errors

**Comment by Rathorian** [comment]
I come back to test and I'm still in "rateLimited".
Too long what!

I'll let you know about the issue

**Comment by denji** [comment]
* https://letsencrypt.org/docs/rate-limits/
* https://letsencrypt.org/docs/staging-environment/#rate-limits

**Comment by Rathorian** [comment]
Thank you Denji but I'm aware, I've already watched the doc.

I find it just amazing because it can not come from:

- The Certificates per Registered Domain limit is 30,000 per week.
- The Duplicate Certificate limit is 30,000 per week.

Because it's just impossible.

And for :

- The Failed Validations limit is 60 per hour.
- The Accounts per IP Address is 50 accounts per 3 hour per IP.

Since yesterday, it should have been good. But no, I'm still in rateLimited.
I do not understand

**Comment by denji** [comment]
You did import the certificate from another format to acme.json?
Perhaps the problem is the mismatch of the chain within the certificate `acme{main/sans}`

**Comment by denji** [comment]
I see that there is a migration method [`dumpcerts.sh`](https://github.com/hardware/mailserver/blob/master/rootfs/usr/local/bin/dumpcerts.sh) & [this](https://github.com/hardware/mailserver/blob/master/rootfs/usr/local/bin/run.sh#L107), but not sure that this method is completely safe.

**Comment by Rathorian** [comment]
So, to be quite honest I have no idea, I do not know all that much. Should it be that @Hardware sees it?
Do you think it could come from there?

**Comment by hardware** [comment]
@denji This method should be safe because dumpcerts.sh is an official script from Traefik repo : 

https://github.com/containous/traefik/blob/master/contrib/scripts/dumpcerts.sh
https://github.com/containous/traefik/blob/master/acme/acme_example.json

I use a fixed major version of Traefik to avoid unexpected changes :

https://github.com/hardware/mailserver/blob/c5fad7eb17ddef039ae61132fe1f60510f86e6b4/docker-compose.sample.yml#L11

And this method is tested : 

https://github.com/hardware/mailserver/blob/c5fad7eb17ddef039ae61132fe1f60510f86e6b4/test/tests.bats#L1192-L1227

@Rathorian We can not help you more. Your domain seems to be rate-limited. Try with another ACME client or ask on Let's Encrypt Community Support : https://community.letsencrypt.org/

**Comment by Rathorian** [comment]
I will try to see on the Let's Encrypt forum.
I'll keep you informed !

Thank you

**Comment by hardware** [comment]
@Rathorian Did you try the SAN method ?

```toml
[acme]
onHostRule = false

[[acme.domains]]
main = "domain.tld"
sans = ["mail.domain.tld", "spam.domain.tld", "postfixadmin.domain.tld", "webmail.domain.tld"]
```

With `onHostRule = true` , Traefik asks one certificate per subdomain, with the SAN method (`onHostRule = false` + `[[acme.domains]]`), Traefik request one certificate with all subdomains in the subjectAlternativeName list.

**Comment by Rathorian** [comment]
No I have not tried but I will do it right away.

On the other hand, does it break the problem that the real domain "domain.tld" points to another server?

In doubt, I show you my DNS zone:

```
; ZONE : domaine.fr
; ------------------------------------------------------------------
$ORIGIN domaine.fr.
$TTL 3600

@                         IN          SOA    ns1.domaine.fr. contact.domaine.fr. (
                                               2018021702 ; Serial
                                               14400      ; Refresh
                                               3600       ; Retry
                                               604800     ; Expire
                                               86400 )    ; Minimum

; NAMESERVERS

@                         IN          NS            ns1.domaine.fr.
@                         IN          NS            ns2.domaine.fr.

; A RECORDS

@                         IN          A             1.1.1.10
ns3                       IN          A             1.1.1.10
ns1                       IN          A             1.1.1.20
mail                      IN          A             1.1.1.20
ns2                       IN          A             1.1.1.30

; AAAA RECORDS

@                         IN          AAAA          2001:41d0:1:XXXX::10
ns3                       IN          AAAA          2001:41d0:1:XXXX::10
ns1                       IN          AAAA          2001:41d0:a:XXXX::20
mail                      IN          AAAA          2001:41d0:a:XXXX::20
ns2                       IN          AAAA          2a03:75c0:25:XXXX::30


; CNAME RECORDS

spam                      IN          CNAME         mail
postfixadmin              IN          CNAME         mail
webmail                   IN          CNAME         mail
sdbx                      IN          CNAME         ns3
emby                      IN          CNAME         ns3
cloud                     IN          CNAME         ns3
www                       IN          CNAME         ns3

; MX RECORDS

@                         IN          MX 10         mail.domaine.fr.
```

**Comment by Rathorian** [comment]
I tried with:

```
# traefik.toml

[acme]
onHostRule = false

[[acme.domains]]
main = "domain.tld"
sans = ["mail.domain.tld", "spam.domain.tld", "postfixadmin.domain.tld", "webmail.domain.tld"]
```

Here is the return of the logs:

```
docker logs -f traefik


legolog: 2018/02/19 11:21:15 [INFO] acme: Registering account for contact@domaine.fr
legolog: 2018/02/19 11:21:18 [INFO][domaine.fr, mail.domaine.fr, spam.domaine.fr, postfixadmin.domaine.fr, webmail.domaine.fr] acme: Obtaining bundled SAN certificate
legolog: 2018/02/19 11:21:19 [INFO][domaine.fr] AuthURL: https://acme-v01.api.letsencrypt.org/acme/authz/BxI5BnANjhZJr9m4jUltbn-_dSHHM5-S9svXqLxF1yM
legolog: 2018/02/19 11:21:19 [INFO][mail.domaine.fr] AuthURL: https://acme-v01.api.letsencrypt.org/acme/authz/kO-UeTrNX0i2bnu8o-QM9a4V7RymvcebYsnY6PuWdU4
legolog: 2018/02/19 11:21:19 [INFO][spam.domaine.fr] AuthURL: https://acme-v01.api.letsencrypt.org/acme/authz/9XvJiJU3RSflmk83s0Adal8fneZsjtCfAHtA_spiyLQ
legolog: 2018/02/19 11:21:19 [INFO][postfixadmin.domaine.fr] AuthURL: https://acme-v01.api.letsencrypt.org/acme/authz/3EagvUB5i4_bjGWfW6zljqmV16C3328t_01F3XdieQE
legolog: 2018/02/19 11:21:19 [INFO][webmail.domaine.fr] AuthURL: https://acme-v01.api.letsencrypt.org/acme/authz/_zcS06Jt-_RsfwKNMt4CCGdtJQtep-mjK5kynBdvatQ
legolog: 2018/02/19 11:21:19 [INFO][domaine.fr] acme: Could not find solver for: dns-01
legolog: 2018/02/19 11:21:19 [INFO][domaine.fr] acme: Trying to solve HTTP-01
legolog: 2018/02/19 11:21:23 [INFO][mail.domaine.fr] acme: Trying to solve HTTP-01
legolog: 2018/02/19 11:21:25 [INFO][mail.domaine.fr] The server validated our request
legolog: 2018/02/19 11:21:25 [INFO][spam.domaine.fr] acme: Could not find solver for: dns-01
legolog: 2018/02/19 11:21:25 [INFO][spam.domaine.fr] acme: Trying to solve HTTP-01
legolog: 2018/02/19 11:21:27 [INFO][spam.domaine.fr] The server validated our request
legolog: 2018/02/19 11:21:27 [INFO][postfixadmin.domaine.fr] acme: Could not find solver for: dns-01
legolog: 2018/02/19 11:21:27 [INFO][postfixadmin.domaine.fr] acme: Trying to solve HTTP-01
legolog: 2018/02/19 11:21:29 [INFO][postfixadmin.domaine.fr] The server validated our request
legolog: 2018/02/19 11:21:29 [INFO][webmail.domaine.fr] acme: Trying to solve HTTP-01
legolog: 2018/02/19 11:21:31 [INFO][webmail.domaine.fr] The server validated our request
time="2018-02-19T11:21:31Z" level=error msg="map[domaine.fr:acme: Error 403 - urn:acme:error:unauthorized - Invalid response from http://domaine.fr/.well-known/acme-challenge/R--his6kWxnkVLrJMbfaz7SQqJUoz2i9hYKDaf4P-Vs [2001:41d0:1:XXXX::10]: 404
Error Detail:
        Validation for domaine.fr:443
        Resolved to:
                1.1.1.10
                2001:41d0:1:XXXX::10
        Used: 1.1.1.10

        Validation for domaine.fr:80
        Resolved to:
                1.1.1.10
                2001:41d0:1:XXXX::10
        Used: 2001:41d0:1:XXXX::10

]"
time="2018-02-19T11:21:31Z" level=error msg="Error getting ACME certificate for domain [domaine.fr mail.domaine.fr spam.domaine.fr postfixadmin.domaine.fr webmail.domaine.fr]: cannot obtain certificates map[domaine.fr:acme: Error 403 - urn:acme:error:unauthorized - Invalid response from http://domaine.fr/.well-known/acme-challenge/R--his6kWxnkVLrJMbfaz7SQqJUoz2i9hYKDaf4P-Vs [2001:41d0:1:XXXX::10]: 404
Error Detail:
        Validation for domaine.fr:443
        Resolved to:
                1.1.1.10
                2001:41d0:1:XXXX::10
        Used: 1.1.1.10

        Validation for domaine.fr:80
        Resolved to:
                1.1.1.10
                2001:41d0:1:XXXX::10
        Used: 2001:41d0:1:XXXX::10

]"
```

**Comment by denji** [comment]
1. acme: Could not find solver for: dns-01
2. acme: Trying to solve HTTP-01
3. validated error page 404 `http://domaine.fr/.well-known/acme-challenge/*`

**Comment by hardware** [comment]
> Because I want to use the real domain "domain.tld" on a different server than on my mail server.

```toml
[[acme.domains]]
main = "mail.domain.tld"
sans = ["spam.domain.tld", "postfixadmin.domain.tld", "webmail.domain.tld"]
```
