### ISSUE TITLE
Add security headers with Traefik

### ISSUE THREAD

**Issue by 1n5aN1aC** [hardware/mailserver#224]
#### Classification
* [X] Question

If this kind of question is more applicable to traefik itself, let me know and I can ask there.
Anyways, I've got your mailserver setup working great, love it, thanks for all the work!

#### Description
I've set up additional website(s) using nginx / apache in new container(s) in my docker-compose, and it works great, traffic is passed through traefik, which handles the ssl as well.
However, I have some TLS settings I'd like to modify, and I need to send HSTS headers at a minimum, preferably for all my traffic through traefik, but at least for this site.

According to the [traefik docs](https://docs.traefik.io/basics/#security-headers/), it's relatively easy to define these in the frontends configuration area, which as I understand is dynamically generated by the labels in my docker-compose.yml

How can I (and where should I) provide these additional settings for traefik?

**Comment by hardware** [comment]
You can use containers STS labels :

```yml
labels:
  - traefik.frontend.headers.STSSeconds=315360000
  - traefik.frontend.headers.STSIncludeSubdomains=true
  - traefik.frontend.headers.STSPreload=true
```

Be careful with `IncludeSubdomains and Preload`, don't request inclusion on Chrome's HSTS preload list unless you're sure that you can **support HTTPS for your entire site and all its subdomains the long term.**

https://docs.traefik.io/configuration/backends/docker/#security-headers

For TLS version and ciphers :

```toml
[entryPoints]
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
    minVersion = "VersionTLS12"
    cipherSuites = [
      "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305",
      "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
    ]
```

https://godoc.org/crypto/tls#pkg-constants

**Comment by 1n5aN1aC** [comment]
Thanks!  I actually had the TLS version and ciphers working great, but am still having issues with the labels...

Here's the relevant section of my docker-compose  (I'm just testing it on the one sub-domain for now):
```
rainloop:
    image: hardware/rainloop
    container_name: rainloop
    restart: ${RESTART_MODE}
    labels:
      - traefik.enable=true
      - traefik.backend.port=8888
      - traefik.frontend.rule=Host:webmail.${DOMAIN}
      - traefik.frontend.headers.STSPreload=true
      - traefik.frontend.headers.STSSeconds=31536000
      - traefik.docker.network=http_network
    volumes:
      - ${VOLUMES_ROOT_PATH}/rainloop:/rainloop/data
    depends_on:
      - mailserver
      - mariadb
    networks:
      - mail_network
      - http_network
```


Strict Transport Security (HSTS) is still showing as "No" both in manual header checks & ssllabs tests, after both `docker-compose up -d` (restarts rainloop) and `docker container restart traefik`.

I'm doing a full `docker-compose down` followed by `docker-compose up -d` to rule any strangeness from that out.  Will report back in a few minutes.

**Comment by 1n5aN1aC** [comment]
Sorry for taking a bit to get back- but a full `docker-compose down` followed by `docker-compose up -d` still isn't making any difference on the `webmail.domain.tld` defined above.

Here's my current traefik.toml:
```
defaultEntryPoints = ["https","http"]

[api]
entryPoint = "traefik"
dashboard = true

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
    cipherSuites = [
      "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
      "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305",
      "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
      "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA",
      "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA"
    ]
  [entryPoints.traefik]
  address = ":8080"
  [entryPoints.traefik.auth.basic]
  users = ["admin:{SHA}snip="]

[acme]
email = "webmaster@mailmag.net"
storage = "/etc/traefik/acme/acme.json"
entryPoint = "https"
onHostRule = true
onDemand = false
  [acme.httpChallenge]
  entryPoint = "http"

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "{{ DOMAIN }}"
watch = true
exposedbydefault = false
```

**Comment by hardware** [comment]
Add `traefik.frontend.headers.isDevelopment=false`

> This will cause the AllowedHosts, SSLRedirect, and STSSeconds/STSIncludeSubdomains options to be ignored during development. When deploying to production, be sure to set this to false.

**Comment by 1n5aN1aC** [comment]
None of that worked, even tried adding additional header options and all kinds of stuff.  However, I did figure out my issue, though I'm trying to decide where to go from here.

According to [the documentation](https://docs.traefik.io/configuration/backends/docker/#labels-overriding-default-behaviour):
```
If you use a compose file, labels should be defined in the deploy part of your service.
This behavior is only enabled for docker-compose version 3+ (Compose file reference).
```

Turns out I'm running an ancient version of docker-compose, (doesn't support compose files >2) since the box is running Debian stable.

....I'm not sure how it gets the `frontend.rule=` and other parts that make it actually work, yet doesn't get the other options, but that's almost certainly why any changes I make aren't being picked up and followed by traefik.

**Comment by denji** [comment]
docker inspect \
  --format "{{ index .Config.Labels \"com.docker.compose.project\"}}" \
  rainloop

**Comment by 1n5aN1aC** [comment]
@denji Yup, that shows all the labels, but again, I think traefik is either not reading those or ignoring them, since I'm running an ancient docker-compose file version.

**Comment by hardware** [comment]
> Turns out I'm running an ancient version of docker-compose, (doesn't support compose files >2) since the box is running Debian stable.

I use Debian stable too with docker 17.12.0-ce and docker-compose 1.19.0 (docker-compose file version <= 3.5 supported). You should update your Docker installation.

https://docs.docker.com/compose/compose-file/#compose-and-docker-compatibility-matrix

**Comment by 1n5aN1aC** [comment]
@hardware interesting.....
I'm running `Docker version 17.12.1-ce`, so updated there, but `docker-compose version 1.8.0`!

`apt install docker-compose` claims that:  `docker-compose is already the newest version (1.8.0-2)`

You're not running backports or anything? the [Debian package database](https://packages.debian.org/stretch/docker-compose) shows 1.8.0-2 as the latest version in the repos....

**Comment by 1n5aN1aC** [comment]
I guess I can just manually update the binary......  I really don't like doing that, but I guess it's that simple.....

**Comment by hardware** [comment]
I don't use APT to update docker-compose.

```bash
curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose
```

**Comment by ksylvan** [comment]
Or another option (which is what I use most often):

https://docs.docker.com/compose/install/#install-compose

```
$ sudo curl -L --fail https://github.com/docker/compose/releases/download/1.19.0/run.sh -o /usr/local/bin/docker-compose
$ sudo chmod +x /usr/local/bin/docker-compose
```

Docker Compose in a container.

**Comment by 1n5aN1aC** [comment]
Alright:
-  docker-compose updated to version `1.19.0`,
-  docker-compose.yml changed to `version: '3'`,
-  everything restarted with `docker-compose down` then `docker-compose up -d` for good measure.

Still no difference.  :/

I'm using a temporary container for testing these changes, which is hosting at hydra.13-thirtyseven.com if you'd like to take a look.

Here is my current config:
```
  php-hydra:
    image: php:7.0-apache
    container_name: php-hydra
    restart: ${RESTART_MODE}
    labels:
      - traefik.enable=true
      - traefik.frontend.headers.isDevelopment=false
      - traefik.frontend.headers.forceSTSHeader=true
      - traefik.frontend.headers.STSPreload=true
      - traefik.frontend.headers.STSSeconds=31536000
      - traefik.frontend.rule=Host:hydra.13-thirtyseven.com
      - traefik.backend.port=80
      - traefik.docker.network=http_network
    volumes:
      - /home/syncthing/Public:/var/www/html
      - /home/syncthing/Backups/Minecraft/Servers:/var/www/html/Minecraft/Servers:ro
    networks:
      - http_network
```

I've tried adding forceSTSHeader, just in case, made no difference.  I've tried putting the headers *before* the frontend host rule, made no difference.

Here is output from:  `docker inspect --format "{{ index .Config.Labels }}" php-hydra`

```map[traefik.frontend.rule:Host:hydra.13-thirtyseven.com com.docker.compose.config-hash:{snip} com.docker.compose.project:docker com.docker.compose.service:php-hydra traefik.backend.port:80 traefik.docker.network:http_network traefik.frontend.headers.forceSTSHeader:true com.docker.compose.oneoff:False com.docker.compose.version:1.19.0 com.docker.compose.container-number:1 traefik.enable:true traefik.frontend.headers.STSPreload:true traefik.frontend.headers.STSSeconds:31536000 traefik.frontend.headers.isDevelopment:false]```

The [Relevant part of the traefik docs](https://docs.traefik.io/configuration/backends/docker/#labels-overriding-default-behaviour)  mentions:  `If you use a compose file, labels should be defined in the deploy part of your service.` but I thought deploy was only used with docker swarms?

Any ideas, or should this problem posted be on the traefik repo?
