### ISSUE TITLE
How to add email to whitelist

### ISSUE THREAD

**Issue by Amine27** [hardware/mailserver#239]
#### Classification
* [X] Question

#### Description
Hello,

Please, any instruction on how to add an email address (not a domain) to a whitelist, to prevent detection as a spam by rspam.

Thank you.

**Comment by hardware** [comment]
I added `WHITELIST_SPAM_ADDRESSES` environment variable. You can use it like this :

```yml
mailserver:
  image: hardware/mailserver:1.1-latest
  environment:
    - WHITELIST_SPAM_ADDRESSES=address@example.com,another@domain.tld
```

```
docker logs -f mailserver 

[INFO] address@example.com,another@domain.tld added to rspamd whitelist
...
```
