### ISSUE TITLE
not signed with DKIM on gersecurity kernel

### ISSUE THREAD

**Issue by WnP** [hardware/mailserver#256]
#### Classification
_Please delete options that are not relevant._

* [X] Question
* [ ] Deliverability issue
* [ ] Crash/Hang/Data loss
* [ ] Serious bug
* [ ] Minor bug
* [ ] Vulnerability
* [ ] Feature/Enhancement
* [ ] Documentation

#### Reproducibility
_Please delete options that are not relevant._

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

#### Docker information
- `docker info`
```
Containers: 8
 Running: 8
 Paused: 0
 Stopped: 0
Images: 9
Server Version: 17.12.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9584b2309e5be604504d4a8ff7ef5def5b42e9a0 (expected: 9b55aab90508bd389d7654c4baf173a981477d55)
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f (expected: 9f9c96235cc97674e935002fc3d78361b696a69e)
init version: 949e6facb77383876aeff8a6944dde66b3089574
Kernel Version: 4.9.65-1-hardened
Operating System: Alpine Linux v3.7
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 5.795GiB
Name: harpsichord
ID: 6T6O:DWC2:CSKS:FVRJ:DIB4:KE2M:YPBG:HRAM:WP23:M2P6:ZB7G:PC5Z
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```
- `docker images hardware/mailserver --digests --filter "dangling=false"`
```
REPOSITORY            TAG                 DIGEST                                                                    IMAGE ID            CREATED             SIZE
hardware/mailserver   1.1-stable          sha256:fe43bf55de789de15bf8a1459ac45c9d4c71a87c54f03a404ff77e5e290a8d7d   bce3d0fb8019        25 hours ago        369MB

```

#### Description
https://www.mail-tester.com and port25.com claim that messages are not signed with DKIM

#### Steps to reproduce
1. Send a mail from a fresh install

#### Expected results
Mail should be signed with DKIM

#### Actual results
Mail are not signed with DKIM

#### Debugging information

- `docker logs mailserver`
```
2018-06-25T10:47:16.976672+00:00 mail postfix/smtpd[2672]: connect from verifier.port25.com[34.209.113.130]
2018-06-25T10:47:16.977085+00:00 mail postfix/smtpd[2672]: warning: connect to Milter service inet:localhost:11332: Cannot assign requested address
2018-06-25T10:47:17.647932+00:00 mail postfix/smtpd[2672]: Anonymous TLS connection established from verifier.port25.com[34.209.113.130]: TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits)
2018-06-25T10:47:18.182860+00:00 mail postfix/smtpd[2672]: 2CA0F180F: client=verifier.port25.com[34.209.113.130]
2018-06-25T10:47:18.515539+00:00 mail postfix/cleanup[2673]: 2CA0F180F: message-id=<1529923634-437299@verifier.port25.com>
2018-06-25T10:47:18.546780+00:00 mail postfix/qmgr[641]: 2CA0F180F: from=<auth-results@verifier.port25.com>, size=9816, nrcpt=1 (queue active)
2018-06-25T10:47:18.556408+00:00 mail dovecot: lmtp(2675): Connect from local
2018-06-25T10:47:18.687225+00:00 mail dovecot: lmtp(user@domain.tld): r+woITbIMFtzCgAAXyb3ng: sieve: msgid=<1529923634-437299@verifier.port25.com>: stored mail into mailbox 'INBOX'
2018-06-25T10:47:18.687508+00:00 mail postfix/lmtp[2674]: 2CA0F180F: to=<user@domain.tld>, relay=mail.domain.tld[private/dovecot-lmtp], delay=0.71, delays=0.57/0/0/0.13, dsn=2.0.0, status=sent (250 2.0.0 <user@domain.tld> r+woITbIMFtzCgAAXyb3ng Saved)
2018-06-25T10:47:18.687761+00:00 mail dovecot: lmtp(2675): Disconnect from local: Successful quit
2018-06-25T10:47:18.688021+00:00 mail postfix/qmgr[641]: 2CA0F180F: removed
```

- port25.com result
```
This message is an automatic response from Port25's authentication verifier
service at verifier.port25.com.  The service allows email senders to perform
a simple check of various sender authentication mechanisms.  It is provided
free of charge, in the hope that it is useful to the email community.  While
it is not officially supported, we welcome any feedback you may have at
<verifier-feedback@port25.com>.

Thank you for using the verifier,

The Port25 Solutions, Inc. team

==========================================================
Summary of Results
==========================================================
SPF check:          pass
"iprev" check:      pass
DKIM check:         none
SpamAssassin check: ham

==========================================================
Details:
==========================================================

HELO hostname:  mail.domain.tld
Source IP:      212.83.137.183
mail-from:      user@domain.tld

----------------------------------------------------------
SPF check details:
----------------------------------------------------------
Result:         pass
ID(s) verified: smtp.mailfrom=user@domain.tld

DNS record(s):
    domain.tld. 60 IN TXT "v=spf1 a mx ip4:212.83.137.183 ~all"
    domain.tld. 60 IN A 212.83.137.92
    domain.tld. 60 IN MX 10 mail.domain.tld.
    mail.domain.tld. 60 IN A 212.83.137.183


----------------------------------------------------------
"iprev" check details:
----------------------------------------------------------
Result:         pass (matches build.mauras.ch)
ID(s) verified: policy.iprev=212.83.137.183

DNS record(s):
    183.137.83.212.in-addr.arpa. 60 IN PTR build.mauras.ch.
    build.mauras.ch. 60 IN A 212.83.137.183


----------------------------------------------------------
DKIM check details:
----------------------------------------------------------
Result:         none (message not signed)
ID(s) verified:⋅

NOTE: DKIM checking has been performed based on the latest DKIM specs
(RFC 4871 or draft-ietf-dkim-base-10) and verification may fail for
older versions.  If you are using Port25's PowerMTA, you need to use
version 3.2r11 or later to get a compatible version of DKIM.

----------------------------------------------------------
SpamAssassin check details:
----------------------------------------------------------
SpamAssassin v3.4.0 (2014-02-07)

Result:         ham (-1.9 points, 5.0 required)

 pts rule name              description
---- ---------------------- --------------------------------------------------
-0.0 SPF_PASS               SPF: sender matches SPF record
-1.9 BAYES_00               BODY: Bayes spam probability is 0 to 1%
                            [score: 0.0000]



==============================================================
Explanation of the possible results (based on RFCs 7601, 7208)
==============================================================


DKIM Results
============

none:  The message was not signed.

pass:  The message was signed, the signature or signatures were
    acceptable to the ADMD, and the signature(s) passed verification
    tests.

fail:  The message was signed and the signature or signatures were
    acceptable to the ADMD, but they failed the verification test(s).

policy:  The message was signed, but some aspect of the signature or
    signatures was not acceptable to the ADMD.

neutral:  The message was signed, but the signature or signatures
    contained syntax errors or were not otherwise able to be
    processed.  This result is also used for other failures not
    covered elsewhere in this list.

temperror:  The message could not be verified due to some error that
    is likely transient in nature, such as a temporary inability to
    retrieve a public key.  A later attempt may produce a final
    result.

permerror:  The message could not be verified due to some error that
    is unrecoverable, such as a required header field being absent.  A
    later attempt is unlikely to produce a final result.


SPF Results
===========

none:  Either (a) no syntactically valid DNS domain name was extracted from
    the SMTP session that could be used as the one to be authorized, or
    (b) no SPF records were retrieved from the DNS.

neutral:  The ADMD has explicitly stated that it is not asserting whether
    the IP address is authorized.

pass:  An explicit statement that the client is authorized to inject mail
    with the given identity.

fail:  An explicit statement that the client is not authorized to use the
    domain in the given identity.

softfail:  A weak statement by the publishing ADMD that the host is probably
    not authorized.  It has not published a stronger, more definitive policy
    that results in a "fail".

temperror:  The SPF verifier encountered a transient (generally DNS) error
    while performing the check.  A later retry may succeed without further
    DNS operator action.

permerror: The domain's published records could not be correctly interpreted.
    This signals an error condition that definitely requires DNS operator
    intervention to be resolved.


"iprev" Results
===============

pass:  The DNS evaluation succeeded, i.e., the "reverse" and
    "forward" lookup results were returned and were in agreement.

fail:  The DNS evaluation failed.  In particular, the "reverse" and
    "forward" lookups each produced results, but they were not in
    agreement, or the "forward" query completed but produced no
    result, e.g., a DNS RCODE of 3, commonly known as NXDOMAIN, or an
    RCODE of 0 (NOERROR) in a reply containing no answers, was
    returned.

temperror:  The DNS evaluation could not be completed due to some
    error that is likely transient in nature, such as a temporary DNS
    error, e.g., a DNS RCODE of 2, commonly known as SERVFAIL, or
    other error condition resulted.  A later attempt may produce a
    final result.

permerror:  The DNS evaluation could not be completed because no PTR
    data are published for the connecting IP address, e.g., a DNS
    RCODE of 3, commonly known as NXDOMAIN, or an RCODE of 0 (NOERROR)
    in a reply containing no answers, was returned.  This prevented
    completion of the evaluation.  A later attempt is unlikely to
    produce a final result.




==========================================================
Original Email
==========================================================

Return-Path: <user@domain.tld>
Received: from mail.domain.tld (212.83.137.183) by verifier.port25.com id h634342e8s4b for <check-auth@verifier.port25.com>; Mon, 25 Jun 2018 10:47:14 +0000 (envelope-from <user@domain.tld>)
Authentication-Results: verifier.port25.com; spf=pass  smtp.mailfrom=user@domain.tld;
 iprev=pass (matches build.other.tld)  policy.iprev=212.83.137.183;
 dkim=none reason="message not signed"
Received: from authenticated-user (mail.domain.tld [127.0.0.1])
        (using TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits))
        (No client certificate requested)
        (Authenticated sender: user@domain.tld)
        by mail.domain.tld (Postfix) with ESMTPSA id 5ED04180F
        for <check-auth@verifier.port25.com>; Mon, 25 Jun 2018 10:47:11 +0000 (UTC)
Date: Mon, 25 Jun 2018 12:47:09 +0200
From: user name <user@domain.tld>
To: check-auth@verifier.port25.com
Subject: just one more test
Message-ID: <20180625104709.GF392@domain.tld>
MIME-Version: 1.0
Content-Type: multipart/signed; micalg=pgp-sha256;
        protocol="application/pgp-signature"; boundary="A9z/3b/E4MkkD+7G"
Content-Disposition: inline


--A9z/3b/E4MkkD+7G
Content-Type: text/plain; charset=us-ascii
Content-Disposition: inline

yep

--A9z/3b/E4MkkD+7G
Content-Type: application/pgp-signature; name="signature.asc"

-----BEGIN PGP SIGNATURE-----

iQEzBAABCAAdFiEE6AYxhRoEKzorQos7MhQ6Lo9QDVcFAlswyC0ACgkQMhQ6Lo9Q
DVdHLAgAiNi/FSGFwDwPgUqUwhSFWP97Voqie1R4DKvKHsVUaLiKvZQ7JVQlVXL8
+vEG/fR3EkBnHeUqO/07CMerrIr9G7wKrwMpkNKDucDy5r2ISo3q2RD4bL8+bQja
MLHPaJMQI9m7NZvcpXFgQEAcqRlZK4DWHxB8W2YMIZEcOzVZtPeqc7KXhagdjCkv
lSR12ZIPj4DMFA5BZD4Oq0q9IS31deSQTw7h5IF5AWt4GJlMFIbrx3MNiJwOHysc
9qjtbtf5rBt6cOZHXz9Aw4nKSsAPymA8FYyLwxjirs44ejzMhjdOx30qsIVr0j7r
wPNIQnkIzYcFNZ0CHTKZDom9jC3Kcw==
=5Eew
-----END PGP SIGNATURE-----

--A9z/3b/E4MkkD+7G--

```

#### Configuration (docker-compose.yml, traefik.toml...etc)

- `docker-compose.yml`
```yaml
version: "3"

# IPv4 only
# docker network create http_network

# IPv4/IPv6 network
# docker network create http_network --ipv6 --subnet "fd00:0000:0000:0000::/64"
# Refer to https://github.com/hardware/mailserver/#ipv6-support for more information.

networks:
  http_network:
    external: true
  mail_network:
    external: false

services:
  traefik:
    image: traefik:1.6-alpine
    container_name: traefik
    restart: ${RESTART_MODE}
    ports:
      - "80:80"
      - "443:443"
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:mail.${MAILSERVER_DOMAIN}
      - traefik.port=8080
      - traefik.docker.network=http_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${VOLUMES_ROOT_PATH}/traefik/traefik.toml:/traefik.toml:ro
      - ${VOLUMES_ROOT_PATH}/traefik/acme:/etc/traefik/acme
    networks:
      - http_network

  mailserver:
    image: hardware/mailserver:${MAILSERVER_DOCKER_TAG}
    container_name: mailserver
    restart: ${RESTART_MODE}
    domainname: ${MAILSERVER_DOMAIN}                    # Mail server A/MX/FQDN & reverse PTR = mail.domain.tld.
    hostname: ${MAILSERVER_HOSTNAME}
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:spam.${MAILSERVER_DOMAIN}
      - traefik.port=11334
      - traefik.docker.network=http_network
    # extra_hosts:                          - Required for external database (on other server or for local databases on host without docker)
    #  - "mariadb:xx.xx.xx.xx"              - Replace with IP address of MariaDB server
    #  - "redis:xx.xx.xx.xx"                - Replace with IP address of Redis server
    ports:
      - "25:25"       # SMTP                - Required
    # - "110:110"     # POP3       STARTTLS - Optional - For webmails/desktop clients
      - "143:143"     # IMAP       STARTTLS - Optional - For webmails/desktop clients
      - "465:465"     # SMTPS      SSL/TLS  - Optional - Enabled for compatibility reason, otherwise disabled
      - "587:587"     # Submission STARTTLS - Optional - For webmails/desktop clients
      - "993:993"     # IMAPS      SSL/TLS  - Optional - For webmails/desktop clients
    # - "995:995"     # POP3S      SSL/TLS  - Optional - For webmails/desktop clients
      - "4190:4190"   # SIEVE      STARTTLS - Optional - Recommended for mail filtering
    environment:
      - DBPASS=${DATABASE_USER_PASSWORD}       # MariaDB database password (required)
      - RSPAMD_PASSWORD=${RSPAMD_PASSWORD}     # Rspamd WebUI password (required)
    # - ADD_DOMAINS=aa.tld, www.bb.tld...      # Add additional domains separated by commas (needed for dkim keys etc.)
    # - ENABLE_POP3=true                       # Enable POP3 protocol
    # - ENABLE_FETCHMAIL=true                  # Enable fetchmail forwarding
    # - DISABLE_CLAMAV=true                    # Disable virus scanning
    # - DISABLE_SIGNING=true                   # Disable DKIM/ARC signing
    # - DISABLE_GREYLISTING=true               # Disable greylisting policy
    # - DISABLE_RATELIMITING=true              # Disable ratelimiting policy
    #
    # Full list : https://github.com/hardware/mailserver#environment-variables
    #
    volumes:
      - ${VOLUMES_ROOT_PATH}/mail:/var/mail
    depends_on:
      - mariadb
      - redis
    networks:
      - mail_network
      - http_network

  # Administration interface
  # https://github.com/hardware/postfixadmin
  # http://postfixadmin.sourceforge.net/
  # Configuration : https://github.com/hardware/mailserver/wiki/Postfixadmin-initial-configuration
  postfixadmin:
    image: hardware/postfixadmin
    container_name: postfixadmin
    restart: ${RESTART_MODE}
    domainname: ${MAILSERVER_DOMAIN}
    hostname: ${MAILSERVER_HOSTNAME}
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:postfixadmin.${MAILSERVER_DOMAIN}
      - traefik.port=8888
      - traefik.docker.network=http_network
    environment:
      - DBPASS=${DATABASE_USER_PASSWORD}
    depends_on:
      - mailserver
      - mariadb
    networks:
      - mail_network
      - http_network

  # Webmail (Optional)
  # https://github.com/hardware/rainloop
  # https://www.rainloop.net/
  # Configuration : https://github.com/hardware/mailserver/wiki/Rainloop-initial-configuration
  rainloop:
    image: hardware/rainloop
    container_name: rainloop
    restart: ${RESTART_MODE}
    labels:
      - traefik.enable=true
      - traefik.port=8888
      - traefik.frontend.rule=Host:webmail.${MAILSERVER_DOMAIN}
      - traefik.docker.network=http_network
    volumes:
      - ${VOLUMES_ROOT_PATH}/rainloop:/rainloop/data
    depends_on:
      - mailserver
      - mariadb
    networks:
      - mail_network
      - http_network

  # Authoritative DNS server (Optional)
  # https://github.com/hardware/nsd-dnssec
  # https://www.nlnetlabs.nl/projects/nsd/
  # Configuration : https://github.com/hardware/mailserver/wiki/NSD-initial-configuration
  # nsd:
  #   image: hardware/nsd-dnssec
  #   container_name: nsd
  #   restart: ${RESTART_MODE}
  #   ports:
  #     - "53:53"
  #     - "53:53/udp"
  #   volumes:
  #     - ${VOLUMES_ROOT_PATH}/nsd/conf:/etc/nsd
  #     - ${VOLUMES_ROOT_PATH}/nsd/zones:/zones
  #     - ${VOLUMES_ROOT_PATH}/nsd/db:/var/db/nsd

  # Database
  # https://github.com/docker-library/mariadb
  # https://mariadb.org/
  mariadb:
    image: mariadb:10.2
    container_name: mariadb
    restart: ${RESTART_MODE}
    # Info : These variables are ignored when the volume already exists (if databases was created before).
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=postfix
      - MYSQL_USER=postfix
      - MYSQL_PASSWORD=${DATABASE_USER_PASSWORD}
    volumes:
      - ${VOLUMES_ROOT_PATH}/mysql/db:/var/lib/mysql
    networks:
      - mail_network

  # Database
  # https://github.com/docker-library/redis
  # https://redis.io/
  redis:
    image: redis:4.0-alpine
    container_name: redis
    restart: ${RESTART_MODE}
    command: redis-server --appendonly yes
    volumes:
      - ${VOLUMES_ROOT_PATH}/redis/db:/data
    networks:
      - mail_network
```
- `traefik.toml`
```toml
defaultEntryPoints = ["https","http"]

[api]
entryPoint = "traefik"
dashboard = true

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
  [entryPoints.traefik]
  address = ":8080"
  [entryPoints.traefik.auth.basic]
  users = ["admin:{SHA}secret/1M="]

[acme]
email = "user@domain.tld"
storage = "/etc/traefik/acme/acme.json"
entryPoint = "https"
onHostRule = true
onDemand = false
  [acme.httpChallenge]
  entryPoint = "http"

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "domain.tld"
watch = true
exposedbydefault = false
```
