### ISSUE TITLE
Certificates not renewed after traefik renewal

### ISSUE THREAD

**Issue by julien1619** [hardware/mailserver#260]
#### Classification

* [X] Documentation

#### Reproducibility

* [X] Always

#### Docker information
```bash
docker info

Containers: 22
 Running: 22
 Paused: 0
 Stopped: 0
Images: 103
Server Version: 18.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.0-6-amd64
Operating System: Debian GNU/Linux 9 (stretch)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.769GiB
Name: vps372101
ID: HG3N:AU5S:2ZDE:OA7F:CEPF:CBDZ:QNGF:JOBS:B5NT:ZBRM:HN53:SS67
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```
```bash
docker images hardware/mailserver --digests --filter "dangling=false"

REPOSITORY            TAG                 DIGEST                                                                    IMAGE ID            CREATED             SIZE
hardware/mailserver   1.1-stable          sha256:3dbb863ed5c714d9b15ff46271bae9c37adfdf57ded53b4f9ea3fefb093129df   e9c99615f126        3 months ago        363MB
```

#### Description

After traefik renewed my certificates, my mailserver wasn't using the new ones. When I did a `ls -al` in the mailserver container to view the certificate folder, I noticed that only the `privkey` and the `fullchain` were recently changed.

To fix it, I had to `docker-compose down` then `up` again to force the `run.sh`script to do its job.

#### Steps to reproduce
1. Let's traefik renewing certificates
2. Use SMTP on 587 with Apple Mail for example

#### Expected results
We expect it to work normally.

#### Actual results
It will complain about an expired certificate.

#### Debugging information
```bash
docker logs mailserver

[INFO] Search for SSL certificates generated by Traefik
[INFO] acme.json found, dumping into pem files
[INFO] Let's encrypt live directory found
[INFO] Using /etc/letsencrypt/live/mail.tiralarc-grand-est.fr folder
[INFO] Found DKIM key pair for domain tiralarc-grand-est.fr - skip creation
[INFO] Found DKIM key pair for domain listes.tiralarc-grand-est.fr - skip creation
[INFO] Override : owner_request_special = no
[INFO] Override : transport_maps = regexp:/opt/mailman/core/var/data/postfix_lmtp
[INFO] Override : local_recipient_maps = regexp:/opt/mailman/core/var/data/postfix_lmtp
[INFO] Override : relay_domains = regexp:/opt/mailman/core/var/data/postfix_domains
[INFO] Custom Postfix configuration file loaded
[INFO] MariaDB/PostgreSQL hostname not found in /etc/hosts
[INFO] Container IP found, adding a new record in /etc/hosts
[INFO] Redis hostname not found in /etc/hosts
[INFO] Container IP found, adding a new record in /etc/hosts
[INFO] ClamAV is disabled, service will not start
[INFO] Fetchmail forwarding is disabled
[INFO] Automatic GPG encryption is disabled
[INFO] ManageSieve protocol is enabled
[INFO] DKIM/ARC signing is enabled
[INFO] Greylisting policy is enabled
[INFO] Ratelimiting policy is enabled
[INFO] POP3 protocol is enabled
[INFO] Unbound DNS resolver is enabled
[INFO] clamav-unofficial-sigs is enabled (user configuration found)
```

#### Configuration (docker-compose.yml, traefik.toml...etc)

```yml
mailserver:
    image: hardware/mailserver:${MAILSERVER_DOCKER_TAG}
    container_name: mailserver
    restart: ${RESTART_MODE}
    domainname: ${MAILSERVER_DOMAIN}                    # Mail server A/MX/FQDN & reverse PTR = mail.domain.tld.
    hostname: ${MAILSERVER_HOSTNAME}
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:spam.${MAILSERVER_DOMAIN}
      - traefik.port=11334
      - traefik.docker.network=http_network
      - traefik.frontend.headers.SSLProxyHeaders=X-Forwarded-Proto:https
      - traefik.frontend.headers.STSSeconds=15768000
      - traefik.frontend.headers.STSIncludeSubdomains=true
      - traefik.frontend.headers.STSPreload=true
      - traefik.frontend.headers.frameDeny=true
      - traefik.frontend.headers.contentTypeNosniff=true
      - traefik.frontend.headers.browserXSSFilter=true
      - traefik.frontend.headers.contentSecurityPolicy=default-src 'self'; script-src 'self' 'unsafe-inline'; img-src 'self' data:; style-src 'self' 'unsafe-inline'; font-src 'self'; frame-src 'self'; object-src 'self'
      - traefik.frontend.headers.referrerPolicy=no-referrer-when-downgrade
    # extra_hosts:                          - Required for external database (on other server or for local databases on host without docker)
    #  - "mariadb:xx.xx.xx.xx"              - Replace with IP address of MariaDB server
    #  - "redis:xx.xx.xx.xx"                - Replace with IP address of Redis server
    ports:
      - "25:25"       # SMTP                - Required
      - "110:110"     # POP3       STARTTLS - Optional - For webmails/desktop clients
      - "143:143"     # IMAP       STARTTLS - Optional - For webmails/desktop clients
    # - "465:465"     # SMTPS      SSL/TLS  - Optional - Enabled for compatibility reason, otherwise disabled
      - "587:587"     # Submission STARTTLS - Optional - For webmails/desktop clients
      - "993:993"     # IMAPS      SSL/TLS  - Optional - For webmails/desktop clients
      - "995:995"     # POP3S      SSL/TLS  - Optional - For webmails/desktop clients
      - "4190:4190"   # SIEVE      STARTTLS - Optional - Recommended for mail filtering
    environment:
      - DBPASS=${DATABASE_USER_PASSWORD}       # MariaDB database password (required)
      - RSPAMD_PASSWORD=${RSPAMD_PASSWORD}     # Rspamd WebUI password (required)
    # - ADD_DOMAINS=aa.tld, www.bb.tld...      # Add additional domains separated by commas (needed for dkim keys etc.)
      - ENABLE_POP3=true                       # Enable POP3 protocol
    # - ENABLE_FETCHMAIL=true                  # Enable fetchmail forwarding
      - DISABLE_CLAMAV=true                    # Disable virus scanning
    # - DISABLE_SIGNING=true                   # Disable DKIM/ARC signing
    # - DISABLE_GREYLISTING=true               # Disable greylisting policy
    # - DISABLE_RATELIMITING=true              # Disable ratelimiting policy
      - RELAY_NETWORKS=172.28.0.2, 172.28.0.3
      - ADD_DOMAINS=listes.${MAILSERVER_DOMAIN}
    #
    # Full list : https://github.com/hardware/mailserver#environment-variables
    #
    volumes:
      - ${VOLUMES_ROOT_PATH}/mail:/var/mail
      - ${VOLUMES_ROOT_PATH}/mailman/core/var/data:/opt/mailman/core/var/data
      - /mnt/docker/traefik/acme:/etc/letsencrypt/acme
    depends_on:
      - mailman-core
      - mariadb
      - redis
    networks:
      mail_network:
      http_network:
      mailman_network:
        ipv4_address: 172.28.0.7
```

```toml
defaultEntryPoints = ["https","http"]

[api]
entryPoint = "traefik"
dashboard = true

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  compress = true
    [entryPoints.https.tls]
    minVersion = "VersionTLS10"
    cipherSuites = [
      "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305",
      "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305",
      "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
      "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
      "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",
      "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
      "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256",
      "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256",
      "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA",
      "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA",
      "TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA",
      "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA"
    ]
  [entryPoints.traefik]
  address = ":8080"
  [entryPoints.traefik.auth.basic]
  users = ["blabla"]

[acme]
email = "blabla"
storage = "/etc/traefik/acme/acme.json"
entryPoint = "https"
onHostRule = true
onDemand = false
  [acme.httpChallenge]
  entryPoint = "http"

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "tiralarc-grand-est.fr"
watch = true
exposedbydefault = false
```
