### ISSUE TITLE
Postfixadmin can't reach MariaDB

### ISSUE THREAD

**Issue by elielam** [hardware/mailserver#309]
#### Classification

* [X] Question

#### Reproducibility

* [x] Always

#### Docker information

$ docker info

```
Containers: 23
 Running: 23
 Paused: 0
 Stopped: 0
Images: 23
Server Version: 18.06.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-34-generic
Operating System: Ubuntu 18.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.28GiB
Name: services
ID: ZAET:O7R4:XJB5:6YCM:D4KF:MMZR:NM7D:LY43:WAGK:4XIR:X64U:AZ5K
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

Portainer network view 

![01ekjcj](https://user-images.githubusercontent.com/34446626/46147195-184d3a80-c265-11e8-9431-e0b5c467888c.png)

$ docker inspect network utilities_network

```
},
        "ConfigOnly": false,
        "Containers": {

             ...

            "2b01fa919d62accf9250340434404bede9da5cbd0cff600142487be4450e2507": {
                "Name": "mailserver",
                "EndpointID": "bdf25bd3f984779ac80a4952ab109c924ae0fada45e359d8e53c6cd829cc46be",
                "MacAddress": "02:42:ac:13:00:04",
                "IPv4Address": "172.19.0.4/16",
                "IPv6Address": ""
            },
            "85d36fca66abf861ee040c5c5d50ba6b0ee82ed128ef0dc3664b094b77d865e5": {
                "Name": "postfixadmin",
                "EndpointID": "4ea61b9a3eb58e3653d25b339475f8f2ebbb40c4e1a3c69015a566201ea6fcec",
                "MacAddress": "02:42:ac:13:00:07",
                "IPv4Address": "172.19.0.7/16",
                "IPv6Address": ""
            },
            "9dab119cd897b71caf1944e6fb6a536ac6ad33c5ac9ec800e683644c377b81fb": {
                "Name": "rainloop",
                "EndpointID": "f4b59d9ffcb54532996e92f180f428c77481956ac5129f4f009a6bc698e97388",
                "MacAddress": "02:42:ac:13:00:06",
                "IPv4Address": "172.19.0.6/16",
                "IPv6Address": ""
            },
            "b730ff5eee3c3b4f1d0d41f7a44c4dc50388357a9587085c151f8738475551db": {
                "Name": "traefik",
                "EndpointID": "73825e788dc3bc8d782a8e016f3acff513417e540ce9edb0483c96077432b5bf",
                "MacAddress": "02:42:ac:13:00:02",
                "IPv4Address": "172.19.0.2/16",
                "IPv6Address": ""
            }
        },
        "Options": {},
        "Labels": {}
    }
```

$ docker inspect network utilities_mail_network

```
},
        "ConfigOnly": false,
        "Containers": {
            "2b01fa919d62accf9250340434404bede9da5cbd0cff600142487be4450e2507": {
                "Name": "mailserver",
                "EndpointID": "2aa2a27b286575391902c82552f7726d0338c64a7e963190220f551e79cb2b56",
                "MacAddress": "02:42:ac:17:00:04",
                "IPv4Address": "172.23.0.4/16",
                "IPv6Address": ""
            },
            "85d36fca66abf861ee040c5c5d50ba6b0ee82ed128ef0dc3664b094b77d865e5": {
                "Name": "postfixadmin",
                "EndpointID": "3964b18db8794bcd640ede1e3ba4b9f2b8ac0fd2d5550c9979d6edba84354390",
                "MacAddress": "02:42:ac:17:00:05",
                "IPv4Address": "172.23.0.5/16",
                "IPv6Address": ""
            },
            "9668f8bf887cdcf10fe51e441553c2d5f84f9fbd27a27a2f24e0bc13b2f43184": {
                "Name": "mail_mariadb",
                "EndpointID": "cbe5785282e283d732be88dd997f5d18f26fa9a2b5f9de27bf25573d2a85162e",
                "MacAddress": "02:42:ac:17:00:02",
                "IPv4Address": "172.23.0.2/16",
                "IPv6Address": ""
            },
            "9dab119cd897b71caf1944e6fb6a536ac6ad33c5ac9ec800e683644c377b81fb": {
                "Name": "rainloop",
                "EndpointID": "1c10738315434f0055b250007eda62fc8d30b7c9846cba9cdc436a9c5063fd13",
                "MacAddress": "02:42:ac:17:00:06",
                "IPv4Address": "172.23.0.6/16",
                "IPv6Address": ""
            },
            "f3a7d2999dc597e178ba6855abad0fc159d303303cf0c5ec7b3f9181535af177": {
                "Name": "mail_redis",
                "EndpointID": "7f1925ba3e0abfba045d0082ae932872646ba5c240b3853d2fc916681d5b065b",
                "MacAddress": "02:42:ac:17:00:03",
                "IPv4Address": "172.23.0.3/16",
                "IPv6Address": ""
            }
        },
        "Options": {},
        "Labels": {}
    }
```

The network db_network serves me to access my different databases via adminer.

#### Description

I am currently experiencing a problem with the configuration of Postfix and Mariadb.
Even after modifying the config.inc.php file postfix seems not be able to reach db.

![akdnijd](https://user-images.githubusercontent.com/34446626/46147205-23a06600-c265-11e8-8d30-c8cbe07b9cc6.png)

docker-compose.yml mariadb conf

```
      - MYSQL_DATABASE=postfix
      - MYSQL_USER=postfix
      - MYSQL_PASSWORD="password"
```

config.inc.php

```
$CONF['database_type'] = 'mysqli';
$CONF['database_host'] = '172.23.0.2';
$CONF['database_user'] = 'postfix';
$CONF['database_password'] = 'password';
$CONF['database_name'] = 'postfix';
```

#### Debugging information

![rtragxs](https://user-images.githubusercontent.com/34446626/46147222-3450dc00-c265-11e8-91b2-41b322f07437.png)

Postfix Web server seems not have any trouble

![30x477t](https://user-images.githubusercontent.com/34446626/46147300-7843e100-c265-11e8-8098-a53b7eed94fe.png)

#### Configuration (docker-compose.yml, traefik.toml...etc)

docker-compose.yml

```
...
mailserver:
    image: hardware/mailserver:1.1-stable
    container_name: mailserver
    restart: always
    depends_on:
      - mail_mariadb
      - mail_redis
    extra_hosts:
      - "mariadb:172.23.0.2"
      - "redis:172.23.0.3"                   
    domainname: ${SERVER_DOMAIN}
    hostname: mail
    networks:
      - utilities_network
      - mail_network
    ports:
      - "25:25"       # SMTP                - Required
      - "143:143"     # IMAP       STARTTLS - Optional - For webmails/desktop clients
      - "587:587"    # Submission STARTTLS - Optional - For webmails/desktop clients
      - "993:993"     # IMAPS      SSL/TLS  - Optional - For webmails/desktop clients
      - "4190:4190"   # SIEVE      STARTTLS - Optional - Recommended for mail filtering
    volumes:
      - /srv/appdata/utilities/mail:/var/mail
    environment:
      - PUID=${USERID}
      - PGID=${GROUPID}
      - TZ=${TIMEZONE}
      - DBPASS=${MAIL_DB_PASSWORD}
      - RSPAMD_PASSWORD=${MAIL_MONITORING_PASSWORD}
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:monitoring.mail.${SERVER_DOMAIN}
      - traefik.port=11334
      - traefik.docker.network=utilities_network
      - traefik.backend=Mail

  postfixadmin:
    image: hardware/postfixadmin
    container_name: postfixadmin
    restart: always
    depends_on:
      - mailserver
      - mail_mariadb
    networks:
      - utilities_network
      - mail_network
    domainname: ${SERVER_DOMAIN}
    hostname: mail
    environment:
      - PUID=${USERID}
      - PGID=${GROUPID}
      - TZ=${TIMEZONE}
      - DBPASS="password"
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:dashboard.mail.${SERVER_DOMAIN}
      - traefik.port=8888
      - traefik.docker.network=utilities_network
      - traefik.backend=Postfixadmin

  rainloop:
    image: hardware/rainloop
    container_name: rainloop
    restart: always
    depends_on:
      - mailserver
      - mail_mariadb
    networks:
      - utilities_network
      - mail_network
    environment:
      - PUID=${USERID}
      - PGID=${GROUPID}
      - TZ=${TIMEZONE}
    volumes:
      - /srv/appdata/utilities/mail/rainloop:/rainloop/data
    labels:
      - traefik.enable=true
      - traefik.port=8888
      - traefik.frontend.rule=Host:web.mail.${SERVER_DOMAIN}
      - traefik.docker.network=utilities_network
      - traefik.backend=Rainloop

  mail_mariadb:
    image: mariadb:10.2
    container_name: mail_mariadb
    restart: always
    networks:
      - mail_network
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - PUID=${USERID}
      - PGID=${GROUPID}
      - TZ=${TIMEZONE}
      - MYSQL_DATABASE=postfix
      - MYSQL_USER=postfix
      - MYSQL_PASSWORD="password"
    volumes:
      - /srv/appdata/utilities/mail/mysql/db:/var/lib/mysql
    labels:
      - traefik.enable=false

  mail_redis:
    image: redis:4.0-alpine
    container_name: mail_redis
    restart: always
    command: redis-server --appendonly yes
    networks:
      - mail_network    
    environment:
      - PUID=${USERID}
      - PGID=${GROUPID}
      - TZ=${TIMEZONE}
    volumes:
      - /srv/appdata/utilities/mail/redis/db:/data
    labels:
      - traefik.enable=false

...

networks:
  mail_network:
    external: false
  utilities_network:
    external:
      name: utilities_network
  db_network:
    external:
      name: db_network
```

Sorry for my bad english you can reply in french if you want.
thank you in advance.

**Comment by navossoc** [comment]
Try to set `DBHOST` in postfixadmin as `mail_mariadb`

```
  postfixadmin:
    image: hardware/postfixadmin
    container_name: postfixadmin
    restart: always
    depends_on:
      - mailserver
      - mail_mariadb
    networks:
      - utilities_network
      - mail_network
    domainname: ${SERVER_DOMAIN}
    hostname: mail
    environment:
      - PUID=${USERID}
      - PGID=${GROUPID}
      - TZ=${TIMEZONE}
      - DBPASS="password"
      - DBHOST=mail_mariadb
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:dashboard.mail.${SERVER_DOMAIN}
      - traefik.port=8888
      - traefik.docker.network=utilities_network
      - traefik.backend=Postfixadmin
```

**Comment by elielam** [comment]
Ok ty, you were right the link between postfix and db is now established.

Now the message had change:

![ehztaur](https://user-images.githubusercontent.com/34446626/46148458-6adc2600-c268-11e8-94eb-ffa584536e73.png)

I had already deal with this error but i don't remember how i fix it ..

**Comment by elielam** [comment]
I've found this ticket, but don't understand what was the problem.

https://github.com/hardware/postfixadmin/issues/15

**Comment by navossoc** [comment]
You should also sync the configs on the `mail_mariadb` service with the `postfixadmin`

```
  mail_mariadb:
    # ...
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - PUID=${USERID}
      - PGID=${GROUPID}
      - TZ=${TIMEZONE}
      - MYSQL_DATABASE=postfix
      - MYSQL_USER=postfix
      - MYSQL_PASSWORD=password
```

```
  postfixadmin:
    # ...
    environment:
      - PUID=${USERID}
      - PGID=${GROUPID}
      - TZ=${TIMEZONE}
      - DBPASS="password"
```

The default database and user are called `postfix`, have you changed it? If so, you may need to set `DBUSER` and `DBNAME` on `postfixadmin` service.

Another problem could be that quotation marks that you are using on the password, may I suggest a simpler password for tests? (without the quotes or special characters) as it may being bad interpreted by the docker (you may need to escape some character).

**Comment by elielam** [comment]
All information describe in docker-compose are right for mail_mariadb i can connect to mysql with user 
> postfix 

and pass 

> password

and i found the postfix db

![bndzy29](https://user-images.githubusercontent.com/34446626/46149709-3158ea00-c26b-11e8-814e-3d229185a3c2.png)

When i reach mariadb from postfixadmin

![ehztaur](https://user-images.githubusercontent.com/34446626/46149746-446bba00-c26b-11e8-932b-8020a7057ba4.png)

**Comment by navossoc** [comment]
Try to get the content of the `/postfixadmin/config.local.php`

```
docker exec postfixadmin cat /postfixadmin/config.local.php
```

It may help, maybe something is being set wrong there...

Take a closer look at the `$CONF['database_...']` variables.

**Comment by elielam** [comment]
You were right thank you very much.

I add DBUSER and DBNAME variables to docker-compose.yml and it's work fine here it's my sample

```
postfixadmin:
    image: hardware/postfixadmin
    container_name: postfixadmin
    restart: always
    depends_on:
      - mailserver
      - mail_mariadb
    networks:
      - utilities_network
      - mail_network
    domainname: ${SERVER_DOMAIN}
    hostname: mail
    environment:
      - PUID=${USERID}
      - PGID=${GROUPID}
      - TZ=${TIMEZONE}
      - DBPASS=password
      - DBHOST=mail_mariadb
      - DBUSER=postfix
      - DBNAME=postfix
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:dashboard.mail.${SERVER_DOMAIN}
      - traefik.port=8888
      - traefik.docker.network=utilities_network
      - traefik.backend=Postfixadmin

 ...

 mail_mariadb:
    image: mariadb:10.2
    container_name: mail_mariadb
    restart: always
    networks:
      - mail_network
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - PUID=${USERID}
      - PGID=${GROUPID}
      - TZ=${TIMEZONE}
      - MYSQL_DATABASE=postfix
      - MYSQL_USER=postfix
      - MYSQL_PASSWORD=password
    volumes:
      - /srv/appdata/utilities/mail/mysql/db:/var/lib/mysql
    labels:
      - traefik.enable=false
```

Ty again for your time.
