### ISSUE TITLE
Use Nginx instead of Traefik

### ISSUE THREAD

**Issue by mario26** [hardware/mailserver#323]
Hello, i would like to use Nginx instead Traefik, how can i achieve this?

I can not find any information on this point, it is just explain that we can use another web server instead of Traefik...

Thank you!

**Comment by Hydrog3n** [comment]
Hello, You need to modify your compose file with your webserver :)

**Comment by mario26** [comment]
Thank you for your reply ! 

But i do not understand something... To make Traefik work with the Postfix docker, in the README it is explained that it is necessary to edit the file "traefik.toml" this one is not it necessary to run the mail server?

So, if i'm your advice, my docker-compose.yml should look like this:

```
services:
     nginx: 
        image: nginx 
        restart: unless-stopped 
        container_name: nginx 
        networks: 
              front:
                   ipv4_address: 172.16.0.10
        volumes:
                - ./logs/nginx/:/var/log/nginx
                - ./config/nginx/:/etc/nginx/conf.d
                - ./config/letsencrypt:/etc/letsencrypt
                - ./www:/var/www/
        links:
                - php
                - mariadb
        ports:
                - 80:80
                - 443:443

  mailserver:
        image: hardware/mailserver
        container_name: mailserver
        restart: unless-stopped 
        domainname: mydomaine.com
        hostname: mail
        ports:
                - "25:25"
                - "110:110"
                - "143:143"
                - "587:587"
                - "993:993"
                - "995:995"
                - "4190:4190"
        environment:
        	- MYSQL_USER=myuser
        	- MYSQL_DATABASE=mydatabase
                - MYSQL_PASSWORD=mypassword
                - RSPAMD_PASSWORD=password <= should i enter just a password for RSPAMD?
        volumes:
                  - /mail:/var/mail
        depends_on:
                  - mariadb
                  - redis
        networks:
              front:
                   ipv4_address: 172.16.0.20
                   
  mariadb: 
        image: mariadb
        restart: unless-stopped
        container_name: mariadb 
        networks:
              front:
                   ipv4_address: 172.16.0.30
        volumes:
                - ./config/mysql:/etc/mysql/conf.d
                - ./data/mysql:/var/lib/mysql
        ports:
                - 8083:3306
                           
  redis:
       image: redis:4.0-alpine
       container_name: redis
       restart: unless-stopped
       command: redis-server --appendonly yes
       networks:
             front:
                  ipv4_address: 172.16.0.40
       volumes:
                - /redis/db:/data

networks:
     front:
       ipam: 
         driver: default 
         config: 
                - subnet: 172.16.0.0/16
```
Can you tell me if this is correct? If not, can you correct me?

I would like to do without the .env file that i do not understand very well...

Thank you for your help!

**Comment by denji** [comment]
docker-labels is only needed on Traefik, because Traefik is able to auto-configure and identify hosts, for nginx to work you need to fully configure all your services

**Comment by mario26** [comment]
Thank you for your reply !

I now understand the usefulness of the .env file and the variables, so I will use it without difficulty ...

For Letsencrypt, I use cerbot installed on the server, I made a symbolic link to my docker files template and I created a volume for this one in Nginx:

```
services: 
     nginx: 
        image: nginx 
        restart: ${RESTART_MODE}
        container_name: nginx 
        networks: 
              front: 
                   ipv4_address: 172.16.0.10
        volumes:
                - ./logs/nginx/:/var/log/nginx
                - ./config/nginx/:/etc/nginx/conf.d
                - ./config/letsencrypt:/etc/letsencrypt <= symbolic link to Letsencrypt
                - ./www:/var/www/ <= symbolic link to my website
        links:
                - php
                - mariadb
        ports:
                - 80:80
                - 443:443
```
Then, since my Vhost, I call the SSL certificate depending on the domain use:

```
server {
	listen 443 ssl http2;
	server_name mail.mydomaine.com;

	root /var/www/mail;
	index index.php;
	
	ssl_certificate /etc/letsencrypt/live/mail.mydomaine.com/fullchain.pem;
	ssl_certificate_key /etc/letsencrypt/live/mail.mydomaine.com/privkey.pem;
	ssl_trusted_certificate /etc/letsencrypt/live/mail.mydomaine.com/chain.pem;

	include /var/www/snippets/ssl.conf;
	include /var/www/snippets/letsencrypt.conf;

	error_log /var/log/nginx/local_error.log;
	access_log /var/log/nginx/local_access.log;

	location ~ \.php$ {
        	fastcgi_pass php:9000;
        	include fastcgi_params;
        	fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        	fastcgi_param DOCUMENT_ROOT $realpath_root;
	}
}
```
I wrote a little bash script for SSL certificate renewal and it works pretty well!

Regarding the certificate for the mail server, I created a web page on my server at this address: mail.mydomaine.com, the domain has a certificate ssl automatically renewed, what should I do for the mail server can use it?

Here is an example :
```
  mailserver:
    image: hardware/mailserver:${MAILSERVER_DOCKER_TAG}
    container_name: mailserver
    restart: ${RESTART_MODE}
    domainname: ${MAILSERVER_DOMAIN}
    hostname: ${MAILSERVER_HOSTNAME}
    networks: 
           front: 
                 ipv4_address: 172.16.0.60
    ports:
      - "25:25"
      - "110:110"
      - "143:143"
      - "587:587"
      - "993:993"
      - "995:995"
      - "4190:4190"
    environment:
      - DBPASS=${DATABASE_USER_PASSWORD}
      - RSPAMD_PASSWORD=${RSPAMD_PASSWORD} 
    volumes:
      - ./data/mail:/var/mail
      - ./config/letsencrypt:/etc/letsencrypt <= symbolic link to Letsencrypt
    depends_on:
      - mariadb
      - redis
```
In this way, the server mail, will find the certificate all alone according to the domain name that I informed him in hostname?

For "RSPAMD", as for other services, should I create a VHOST in Nginx to display it for example at this address: spam.mydomaine.com?

Exemple VHOST for "RSPAMD" in Nginx:
```
server {
     listen 443 ssl http2;
     server_name spam.mydomaine.com;
    
	ssl_certificate /etc/letsencrypt/live/spam.mydomaine.com/fullchain.pem;
	ssl_certificate_key /etc/letsencrypt/live/spam.mydomaine.com/privkey.pem;
	ssl_trusted_certificate /etc/letsencrypt/live/spam.mydomaine.com/chain.pem;

	include /var/www/snippets/ssl.conf;
	include /var/www/snippets/letsencrypt.conf;

	error_log /var/log/nginx/local_error.log;
	access_log /var/log/nginx/local_access.log;

    location / {
        proxy_pass http://172.16.0.60:11334; #Adresse IP du container
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_read_timeout 90;
    }
}
```
Regarding the password for the "rspamd" database, should to display the web part of "rspamd" for setup database?

Thank you for your help
