### ISSUE TITLE
documentation incorrect regarding postfix override.

### ISSUE THREAD

**Issue by ragboy** [hardware/mailserver#328]
#### Classification
_Please delete options that are not relevant._
* [X ] Documentation

#### Reproducibility
_Please delete options that are not relevant._

* [X] Always

#### Description
Check your documentation on postfix configuration, according to your run.sh file, the actual file that needs to be created is: /var/mail/postfix/custom.conf

**Comment by navossoc** [comment]
The path is right...

`mnt/docker/mail/postfix/custom.conf` resolves to `/var/mail/postfix/custom.conf`.

Just look at the `docker-compose.sample.yml`:

```
services:
  mailserver:
  // ...
  volumes:
      - ${VOLUMES_ROOT_PATH}/mail:/var/mail
```

And `sample.env`

```
# Docker volumes parent folder
VOLUMES_ROOT_PATH=/mnt/docker
```
