### ISSUE TITLE
Question: Multiple domain SSL

### ISSUE THREAD

**Issue by bkraul** [hardware/mailserver#332]
#### Classification
_Please delete options that are not relevant._

* [X] Question

#### Reproducibility
_Please delete options that are not relevant._

* [X] Not applicable

#### Question:
Hey man, quick question. I am trying to set up my SSL certificates in a multi-domain mail server situation. Basically I used to have a server that that multiple domains (web hosting), and each had is own virtual mail access, with its own mail.domain.tld configuration.

I have my primary mail.domain.tld ssl certificate working great. However, the additional domain I have, even though I have put the certificates in /live/mail.domain2.tld, the mailserver keeps trying to use the SSL cert for the mail.domain.tld. Am I missing something, and mailserver only supports one SSL certificate?

Thanks!

**Comment by navossoc** [comment]
Where do you want to use this extra certificates exactly? On the POPS/IMAPS services?

If so, `dovecot` needs some extra configuration to work with SNI.
https://wiki.dovecot.org/SSL/DovecotConfiguration

If you want to serve the certificate on the SMTPS service too, `postfix` will need some  extra configuration too.
Something like this: https://lxadm.com/Postfix_and_multiple_SSL_certificates

To be honest, depending on your reason, I do not think all this work worth it.

**Comment by bkraul** [comment]
So, basically, in order to connect to the IMAP/SMTP account with a client for mailbox@domain.tld, you set your client to connect to mail.domain.tld, which then supplies the proper SSL certificate that matches the mail domain.

So I have a second domain, which has been added to the mailserver using ADD_DOMAINS. Everything it's setup at the DNS level for that second domain, to use mail.domain2.tld (DKIM, SPF, etc). My expectation is that when setting up my client to connect to mailbox mailbox@domain2.tld, (by connecting to mail.domain2.tld) that the SSL certificate for domain2.tld would be used, but instead, it uses domain.tld, which causes the client to tell me the certificate does not match the domain.

**Comment by sknight80** [comment]
@hardware like this in traefik?
```
[[acme.domains]]
main = "domain.tld"
sans = ["mail.domain.tld", "spam.domain.tld", "postfixadmin.domain.tld", "webmail.domain.tld",
"mail.domain2.tld", "spam.domain2.tld", "postfixadmin.domain2.tld", "webmail.domain2.tld"]
```

**Comment by SCOPEKL** [comment]
Hi @bkraul 

I am new, can you share some guide on how to run multiple domain on same server using hardware/mailserver

maybe you can disguise your configuration by putting 

domain1.com domain2.com domain3.com

I need to run 3 domain in one server, each having their own email and website. Thanks for your help.

**Comment by denji** [comment]
@sknight80 https://docs.traefik.io/configuration/acme/#domains
```ini
[acme]
# ...
[[acme.domains]]
  main = "local1.com"
  sans = ["test1.local1.com", "test2.local1.com"]
[[acme.domains]]
  main = "local2.com"
[[acme.domains]]
  main = "*.local3.com"
  sans = ["local3.com", "test1.test1.local3.com"]
# ...
````

**Comment by bkraul** [comment]
Well, as you can see from this issue, that is a complicated question. Mailserver supports only one SSL wildcard / SAN certificate.

For me, this means I only have one single receiving/sending mail domain (mail.domain.tld), and then the additional domains for mailboxes and such. I also use a third party sending service, which allows me to not have to mess with spam blacklisting etc, etc.

Also, I do not use traefik, I use jwilder/nginx proxy, with docker-compose. I have one single primary domain and then I do subdomains for all my supported domains in order to access rainloop through webmail.domain.tld.

Here is my docker-compose:
```yml
    version: '3'

    services:
      mailserver:
        image: hardware/mailserver:1.1-latest
        container_name: mailserver
        restart: always
        domainname: mymaindomain.com
        hostname: mail
        ports:
          - '25:25'
          - '465:465'
          - '587:587'
          - '993:993'
          - '995:995'
          - '4190:4190'
        environment:
          - DBHOST=db.mymaindomain.com
          - DBUSER=postfix
          - DBPASS=password
          - RSPAMD_PASSWORD=password
          - VIRTUAL_HOST=spam.mymaindomain.com
          - VIRTUAL_PORT=11334
          - DISABLE_CLAMAV=true
          # all local ip segments.
          - RELAY_NETWORKS=192.168.0.0/16 172.16.0.0/12 10.0.0.0/8 
          - ADD_DOMAINS=domain2.com,domain3.com
          - ENABLE_POP3=true
        volumes:
          - /root/docker-persist/mailserver/mail:/var/mail
          - /root/docker-persist/mailserver/mail/postfix/custom:/etc/postfix/custom
          - /root/docker-persist/mailserver/mail/ssl/letsencrypt:/etc/letsencrypt
        depends_on:
          - redis
        networks:
          - reverse-proxy
          - default
      postfixadmin:
        image: hardware/postfixadmin
        container_name: postfixadmin
        restart: always
        domainname: mymaindomain.com
        hostname: mail
        environment:
          - DBHOST=db.mymaindomain.com
          - DBUSER=postfix
          - DBPASS=password
          - PASSVAL_MIN_DIGIT=1
          - VIRTUAL_HOST=postfixadmin.mymaindomain.com
          - VIRTUAL_PORT=8888
        networks:
          - default
          - reverse-proxy
      rainloop:
        image: hardware/rainloop
        container_name: rainloop
        restart: always
        volumes:
          - /root/docker-persist/mailserver/rainloop:/rainloop/data
        environment:
          - VIRTUAL_HOST=webmail.mymaindomain.com, webmail.domain2.com, webmail.domain3.com
          - VIRTUAL_PORT=8888
          - LOG_TO_STDOUT=true
        depends_on:
          - mailserver
        networks:
          - default
          - reverse-proxy
      redis:
        image: redis:4.0-alpine
        container_name: mailserver_redis
        restart: always
        command: redis-server --appendonly yes
        volumes:
          - /root/docker-persist/mailserver/redis/db:/data
        sysctls:
          - net.core.somaxconn=511
        networks:
          - default

    networks:
      reverse-proxy:
        external:
          name: reverse-proxy
```
As you can see, I store my persisted volumes on root's home. This might not work for you, but you can adjust, I suppose.

I get my main wildcard, SAN certificate manually using the letsencrypt container [certbot/certbot](certbot/certbot) and place the files in the letsencrypt folder.

```reverse-proxy``` is a stand-alone bridged network I have created that all my containers can access, which runs for an instance of the jwilder/nginx-proxy image.

Sorry if this is confusing for you as you are starting, but this is the setup that currently works quite well for me.
