### ISSUE TITLE
Multiple domains for accessing webmail and postfixadmin

### ISSUE THREAD

**Issue by enbits** [hardware/mailserver#333]
#### Classification
_Please delete options that are not relevant._

* [X] Question

#### Description
I have a successful setup with multiple virtual hosts:

mail.domain1.com (main domain)
mail.domain2.com
mail.domain3.com

However I can only access to postfix admin and webmail with the main domain:

webmail.domain1.com -> works
webmail.domain2.com -> doesn't work

Do I have to modify traefik config on can this be solved by adding CNAMES? None of the things I've tried worked.

**Comment by hardware** [comment]
```yml
rainloop:
    image: hardware/rainloop
    container_name: rainloop
    restart: ${RESTART_MODE}
    labels:
      - traefik.enable=true
      - traefik.port=8888
      - traefik.frontend.rule=Host:traefik.frontend.rule=Host:webmail.domain1.com,webmail.domain2.com
      - traefik.docker.network=http_network
```
