### ISSUE TITLE
PostfixAdmin login failed

### ISSUE THREAD

**Issue by mario26** [hardware/mailserver#337]
Hello,

I just put up your Postfixadmin docker, before i used a hard Postfixadmin version on the server.

I no problem with the mail server, everything works, i receive and send my mails normaly.

My problem with Postfixadmin, i can not identify myself on the administration of the site:

`PostfixAdmin login failed (username: test@test.org, ip_address: 172.14.0.10)`

I have the impression that he does not use the right method to connect or that he does not find the database?

Here is my configuration:

```
postfixadmin:
    	image: hardware/postfixadmin # Image à installer
    	#restart: ${RESTART_MODE} # Rédémarrer le container si le serveur redémarre (prod)
    	container_name: postfixadmin # Nom du container
    	networks: # Déclarer un réseau
              front: # Section du réseau
                  ipv4_address: 172.14.0.100 # Adresse IP du container
    	environment:
      		- DBPASS=${DATABASE_USER_PASSWORD}
    	depends_on:
      		- mailserver
      		- mariadb
```

I try to generate a new user through the setup.php but it does not work either, it asks me to add the setup_password:

Setup password not specified correctly

```
If you want to use the password you entered as setup password, edit config.inc.php or config.local.php and set

$CONF['setup_password'] = '902e0713b30fbe6ebe0c68b8a449109a:fe5b4092d6e8c26becc788249245330a38561a8e';

```
How can I proceed? I use Nginx, the site is displayed well, but the connection to the administration is imppossible ...

Thank you
