### ISSUE TITLE
Unexpected supervisor crash, mailserver down.

### ISSUE THREAD

**Issue by bkraul** [hardware/mailserver#372]
#### Classification
_Please delete options that are not relevant._

* [ ] Question
* [ ] Deliverability issue
* [x] Crash
* [ ] Serious bug
* [ ] Minor bug
* [ ] Vulnerability
* [ ] Feature/Enhancement
* [ ] Documentation

#### Reproducibility
Random stoppage of the mailserver with the following significant log entries:
```
mailserver      | 2019-04-23T04:30:16.943918+00:00 mail dovecot: master: Warning: Killed with signal 15 (by pid=521 uid=0 code=kill)
mailserver      | s6-svc: fatal: unable to control /services/rsyslogd: supervisor not listening
mailserver      | s6-svc: fatal: unable to control /services/unbound: supervisor not listening
```
* [ ] Always
* [x] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

It would seem as if supervisor is crashing and not coming back.

#### Docker information
```
docker info
----
Containers: 39
 Running: 39
 Paused: 0
 Stopped: 0
Images: 73
Server Version: 18.09.5
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: bb71b10fd8f58240ca47fbb579b9d1028eea7c84
runc version: 2b18fe1d885ee5083ef9f0838fee39b62d653e30
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-47-generic
Operating System: Ubuntu 18.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.852GiB
Name: ********
ID: ******************************
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

WARNING: No swap limit support
----
docker images hardware/mailserver --digests --filter "dangling=false"
REPOSITORY            TAG                 DIGEST                                                                    IMAGE ID            CREATED             SIZE
hardware/mailserver   1.1-latest          sha256:3a5f3349cef7babb07ad51fea1f4b66bce2fd1bc7c1aca69017cf81647a80994   62394a202d82        9 days ago          380MB
```

#### Description
Briefly describe the problem you are having in a few lines.

#### Steps to reproduce
1. Normal operation of mailserver.

#### Expected results
No unexpected supervisor crash.

#### Actual results
Supervisor crashes, docker container restart is needed.

#### Debugging information
```
docker logs mailserver
(relevant)
mailserver      | 2019-04-23T04:21:15.640941+00:00 mail postfix/anvil[2351]: statistics: max connection rate 2/60s for (smtps:***.**.**.**) at Apr 23 04:17:47
mailserver      | 2019-04-23T04:21:15.640986+00:00 mail postfix/anvil[2351]: statistics: max connection count 1 for (smtp:***.***.***.***) at Apr 23 04:15:22
mailserver      | 2019-04-23T04:21:15.641024+00:00 mail postfix/anvil[2351]: statistics: max cache size 2 at Apr 23 04:17:44
mailserver      | 2019-04-23T04:23:21.741196+00:00 mail postfix/smtpd[2363]: warning: hostname hosting-by.directwebhost.org does not resolve to address **.***.***.**
mailserver      | 2019-04-23T04:23:21.741322+00:00 mail postfix/smtpd[2363]: connect from unknown[**.***.***.**]
mailserver      | 2019-04-23T04:23:22.626798+00:00 mail postfix/smtpd[2363]: lost connection after EHLO from unknown[**.***.***.**]
mailserver      | 2019-04-23T04:23:22.627014+00:00 mail postfix/smtpd[2363]: disconnect from unknown[**.***.***.**] ehlo=1 commands=1
mailserver      | 2019-04-23T04:23:36.835359+00:00 mail postfix/smtpd[2363]: connect from unknown[185.234.219.64]
mailserver      | 2019-04-23T04:23:37.243754+00:00 mail postfix/smtpd[2363]: lost connection after AUTH from unknown[185.234.219.64]
mailserver      | 2019-04-23T04:23:37.244038+00:00 mail postfix/smtpd[2363]: disconnect from unknown[185.234.219.64] ehlo=1 auth=0/1 commands=1/2
mailserver      | 2019-04-23T04:25:32.469899+00:00 mail postfix/smtpd[2366]: connect from lputeaux-656-1-115-122.w193-251.abo.wanadoo.fr[193.251.18.122]
mailserver      | 2019-04-23T04:25:32.766128+00:00 mail postfix/smtpd[2366]: lost connection after AUTH from lputeaux-656-1-115-122.w193-251.abo.wanadoo.fr[193.251.18.122]
mailserver      | 2019-04-23T04:25:32.766537+00:00 mail postfix/smtpd[2366]: disconnect from lputeaux-656-1-115-122.w193-251.abo.wanadoo.fr[193.251.18.122] helo=1 auth=0/1 commands=1/2
mailserver      | 2019-04-23T04:28:52.964062+00:00 mail postfix/anvil[2365]: statistics: max connection rate 1/60s for (smtp:**.***.***.**) at Apr 23 04:23:21
mailserver      | 2019-04-23T04:28:52.964102+00:00 mail postfix/anvil[2365]: statistics: max connection count 1 for (smtp:**.***.***.**) at Apr 23 04:23:21
mailserver      | 2019-04-23T04:28:52.964126+00:00 mail postfix/anvil[2365]: statistics: max cache size 2 at Apr 23 04:23:36
mailserver      | 2019-04-23T04:29:38.877835+00:00 mail postfix/smtpd[2368]: connect from unknown[185.234.219.64]
mailserver      | 2019-04-23T04:29:39.236061+00:00 mail postfix/smtpd[2368]: lost connection after AUTH from unknown[185.234.219.64]
mailserver      | 2019-04-23T04:29:39.236707+00:00 mail postfix/smtpd[2368]: disconnect from unknown[185.234.219.64] ehlo=1 auth=0/1 commands=1/2
mailserver      | 2019-04-23T04:30:16.943918+00:00 mail dovecot: master: Warning: Killed with signal 15 (by pid=521 uid=0 code=kill)
mailserver      | [INFO] Traefik SSL certificates not used
mailserver      | [INFO] Let's encrypt live directory found
mailserver      | [INFO] Using /etc/letsencrypt/live/mail.mydomain.com folder
mailserver      | [INFO] Found DKIM key pair for domain *******.com - skip creation
mailserver      | [INFO] Found DKIM key pair for domain *******.com - skip creation
mailserver      | [INFO] Found DKIM key pair for domain ******.com - skip creation
mailserver      | [INFO] Found DKIM key pair for domain ********.com - skip creation
mailserver      | [INFO] Found DKIM key pair for domain ******.com - skip creation
mailserver      | [INFO] Found DKIM key pair for domain ******.com - skip creation
mailserver      | [INFO] Found DKIM key pair for domain ******.com - skip creation
mailserver      | [INFO] Found DKIM key pair for domain *****.com - skip creation
mailserver      | [INFO] Found DKIM key pair for domain *****.com - skip creation
mailserver      | [INFO] Found DKIM key pair for domain *****.com - skip creation
mailserver      | [INFO] Found DKIM key pair for domain *****.com - skip creation
mailserver      | [INFO] Found DKIM key pair for domain *****.com - skip creation
mailserver      | [INFO] Found DKIM key pair for domain *****.com - skip creation
mailserver      | [INFO] Override parameter in main.cf : smtpd_sender_restrictions=reject_non_fqdn_sender,reject_unknown_sender_domain,permit_mynetworks,reject_sender_login_mismatch,reject_rhsbl_sender dbl.spamhaus.org
mailserver      | [INFO] Override parameter in main.cf : relayhost = [**.********.com]:587
mailserver      | [INFO] Override parameter in main.cf : smtp_sasl_auth_enable = yes
mailserver      | [INFO] Override parameter in main.cf : smtp_sasl_security_options = noanonymous
mailserver      | [INFO] Override parameter in main.cf : smtp_sasl_password_maps = hash:/etc/postfix/custom/sasl_passwd
mailserver      | [INFO] Override service parameter in master.cf : submission/inet/smtpd_client_restrictions=permit_mynetworks,permit_sasl_authenticated,reject
mailserver      | [INFO] Override service parameter in master.cf : smtps/inet/smtpd_client_restrictions=permit_mynetworks,permit_sasl_authenticated,reject
mailserver      | [INFO] Custom Postfix configuration file loaded
mailserver      | [INFO] MariaDB/PostgreSQL hostname not found in /etc/hosts
mailserver      | [INFO] Container IP found, adding a new record in /etc/hosts
mailserver      | [INFO] Redis hostname not found in /etc/hosts
mailserver      | [INFO] Container IP found, adding a new record in /etc/hosts
mailserver      | [INFO] Debug mode is disabled
mailserver      | [INFO] ClamAV is disabled, service will not start
mailserver      | [INFO] Fetchmail forwarding is disabled
mailserver      | [INFO] Automatic GPG encryption is disabled
mailserver      | [INFO] ManageSieve protocol is enabled
mailserver      | [INFO] DKIM/ARC signing is enabled
mailserver      | [INFO] Greylisting policy is enabled
mailserver      | [INFO] Ratelimiting policy is disabled
mailserver      | [INFO] POP3 protocol is enabled
mailserver      | [INFO] Unbound DNS resolver is enabled
mailserver      | [INFO] clamav-unofficial-sigs is disabled (user configuration not found)
mailserver      | s6-svc: fatal: unable to control /services/rsyslogd: supervisor not listening
mailserver      | s6-svc: fatal: unable to control /services/unbound: supervisor not listening
```
#### Configuration (docker-compose.yml, traefik.toml...etc)
```yml
version: '3'

services:
  mailserver:
    image: hardware/mailserver:1.1-latest
    container_name: mailserver
    restart: always
    domainname: mydomain.com
    hostname: mail
    ports:
      - '25:25'
      - '465:465'
      - '587:587'
      - '993:993'
      - '995:995'
      - '4190:4190'
    environment:
      - DBHOST=vps.mydomain.com
      - DBUSER=*********
      - DBPASS=********
      - RSPAMD_PASSWORD=**********
      - VIRTUAL_HOST=spam.mydomain.com
      - VIRTUAL_PORT=11334
      - DISABLE_CLAMAV=true
      - RELAY_NETWORKS=192.168.0.0/16 172.16.0.0/12 10.0.0.0/8
      - ADD_DOMAINS=domain1.com,domain2.com,domain3.com
      - ENABLE_POP3=true
    volumes:
      - /root/docker-persist/mailserver/mail:/var/mail
      - /root/docker-persist/mailserver/mail/postfix/custom:/etc/postfix/custom
      - /root/docker-persist/mailserver/mail/ssl/letsencrypt:/etc/letsencrypt
    depends_on:
      - redis
    networks:
      - reverse-proxy
      - default
  postfixadmin:
    image: hardware/postfixadmin
    container_name: postfixadmin
    restart: always
    domainname: mydomain.com
    hostname: mail
    environment:
      - DBHOST=vps.mydomain.com
      - DBUSER=*******
      - DBPASS=*******
      - PASSVAL_MIN_DIGIT=1
      - VIRTUAL_HOST=postfixadmin.mydomain.com
      - VIRTUAL_PORT=8888
    networks:
      - default
      - reverse-proxy
  rainloop:
    image: hardware/rainloop
    container_name: rainloop
    restart: always
    volumes:
      - /root/docker-persist/mailserver/rainloop:/rainloop/data
    environment:
      - VIRTUAL_HOST=domain1,com,domain2.com,domain3.com
      - VIRTUAL_PORT=8888
      - LOG_TO_STDOUT=true
    depends_on:
      - mailserver
    networks:
      - default
      - reverse-proxy
  redis:
    image: redis:4.0-alpine
    container_name: mailserver_redis
    restart: always
    command: redis-server --appendonly yes
    volumes:
      - /root/docker-persist/mailserver/redis/db:/data
    sysctls:
      - net.core.somaxconn=511
    networks:
      - default

networks:
  reverse-proxy:
    external:
      name: reverse-proxy
```
