### ISSUE TITLE
Invalid query: Table 'postfix.config' doesn't exist

### ISSUE THREAD

**Issue by RealPolluX** [hardware/mailserver#380]
#### Classification
* [X] Question

#### Reproducibility
* [X] Always

#### Docker information

docker info:
```
root@mail:/mnt/docker/mail# docker info
Containers: 6
 Running: 6
 Paused: 0
 Stopped: 0
Images: 6
Server Version: 18.09.6
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: bb71b10fd8f58240ca47fbb579b9d1028eea7c84
runc version: 2b18fe1d885ee5083ef9f0838fee39b62d653e30
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.0-9-amd64
Operating System: Debian GNU/Linux 9 (stretch)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.8GiB
Name: mail
ID: PZ7E:7IHS:BBYF:LDZ4:6PNM:KVCZ:S3SZ:LTM4:ZXRY:D72T:Z2F5:RI5I
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

WARNING: No swap limit support
```

docker images hardware/mailserver --digests --filter "dangling=false":
```
REPOSITORY            TAG                 DIGEST                                                                    IMAGE ID            CREATED             SIZE
hardware/mailserver   1.1-stable          sha256:0af0d6bb7d5de589cb1cf47811f844d7ed43827a3298197fdd4cafee8d2c8ed5   1d08ae0bb068        5 weeks ago         380MB
```

#### Description
When installing / setting up the mailserver and afterwards trying to login to the postfixadmin page, an error is shown (see below).

#### Steps to reproduce
1. Install docker like it is described here: https://docs.docker.com/install/linux/docker-ce/debian/
2. Configure/Set up the mailserver like it is described here: https://hub.docker.com/r/hardware/mailserver#system-requirements
3. visit https://postfixadmin.domain.tld/login.php

#### Expected results
login available and no error page

#### Actual results
a white page which shows: 
```
DEBUG INFORMATION:
Invalid query: Table 'postfix.config' doesn't exist

Check your error_log for the failed query.

Please check the documentation and website for more information.
```

#### Configuration (docker-compose.yml, traefik.toml...etc)

docker-compose.yml (only postfix related):
```
  # Administration interface
  # https://github.com/hardware/postfixadmin
  # http://postfixadmin.sourceforge.net/
  # Configuration : https://github.com/hardware/mailserver/wiki/Postfixadmin-initial-configuration
  postfixadmin:
    image: hardware/postfixadmin
    container_name: postfixadmin
    restart: ${RESTART_MODE}
    domainname: ${MAILSERVER_DOMAIN}
    hostname: ${MAILSERVER_HOSTNAME}
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:postfixadmin.${MAILSERVER_DOMAIN}
      - traefik.port=8888
      - traefik.docker.network=http_network
    environment:
      - DBPASS=${DATABASE_USER_PASSWORD}
    depends_on:
      - mailserver
      - mariadb
    networks:
      - mail_network
      - http_network
```
