### ISSUE TITLE
Running in Docker Swarm

### ISSUE THREAD

**Issue by chris579** [hardware/mailserver#399]
#### Classification

* [X] Crash/Hang/Data loss

#### Reproducibility

* [X] Always
#### Docker information
```
Client:
 Debug Mode: false

Server:
 Containers: 23
  Running: 17
  Paused: 0
  Stopped: 6
 Images: 36
 Server Version: 19.03.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: oy2wz9c0t9dvtlwtts1kf0lax
  Is Manager: true
  ClusterID: ilj00ndvvsvujjjho3b1n7mke
  Managers: 1
  Nodes: 1
  Default Address Pool: 10.0.0.0/8
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 89.163.145.239
  Manager Addresses:
   89.163.145.239:2377
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.9.0-9-amd64
 Operating System: Debian GNU/Linux 9 (stretch)
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 31.29GiB
 Name: ve493
 ID: WHBV:FWJS:IDS6:MVRH:HD4F:MYQS:UPCC:BAX3:2MAV:ZGBT:4HZD:3AAG
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: chris579
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support

REPOSITORY            TAG                 DIGEST                                                                    IMAGE ID            CREATED             SIZE
hardware/mailserver   1.1-stable          sha256:9a02ef4864c50576bb007abaeb051db291df694c1cf102b93ccd13d32bc5aeb6   da62912234e5        2 weeks ago         375MB
```

#### Description
I'm switching all my containers to Docker Swarm. When trying to start the container the mailserver container crashes with the following output:
```
mail_mailserver.0.gv5dqwunshnj@ve493    |  [ERROR] The domain name must be set !
```

The parameter `domainname` is not supported for Docker Swarm. However, a friend of mine also uses this image in his Swarm and has no problems. His docker-compose.yml is almost identical.

#### Steps to reproduce
1. Create a docker-compose.yml file with the below content
2. Create a new stack with `docker stack deploy -c <(docker-compose config) mail`
3. Inspect stack logs and see the crash

#### Expected results
The server starts as usual.

#### Actual results
The server doesn't start.

#### Debugging information
```
mail_mailserver.0.gv5dqwunshnj@ve493    |  [ERROR] The domain name must be set !
```

#### Configuration (docker-compose.yml, traefik.toml...etc)
```yaml
services:
  mailserver:
    image: hardware/mailserver:${MAILSERVER_DOCKER_TAG}
    domainname: ${MAILSERVER_DOMAIN}                    # Mail server A/MX/FQDN & reverse PTR = mail.domain.tld.
    hostname: ${MAILSERVER_HOSTNAME}
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
      labels:
        - traefik.enable=true
        - traefik.frontend.rule=Host:${MAILSERVER_HOSTNAME}.${MAILSERVER_DOMAIN}
        - "traefik.frontend.headers.customResponseHeaders=Strict-Transport-Security:15552000"
        - traefik.port=11334
        - traefik.backend=${MAILSERVER_HOSTNAME}.${MAILSERVER_DOMAIN}
        - traefik.docker.network=traefik_reverseproxy
    ports:
      - "25:25"       # SMTP                - Required
      - "143:143"     # IMAP       STARTTLS - Optional - For webmails/desktop clients
      - "587:587"     # Submission STARTTLS - Optional - For webmails/desktop clients
      - "993:993"     # IMAPS      SSL/TLS  - Optional - For webmails/desktop clients
      - "4190:4190"   # SIEVE      STARTTLS - Optional - Recommended for mail filtering
    environment:
      - DBPASS=${DATABASE_USER_PASSWORD}       # MariaDB database password (required)
      - RSPAMD_PASSWORD=${RSPAMD_PASSWORD}     # Rspamd WebUI password (required)
    #
    # Full list : https://github.com/hardware/mailserver#environment-variables
    #
    volumes:
      - ./data/mail:/var/mail
      - ./../traefik/data:/etc/letsencrypt/acme
    depends_on:
      - mariadb
      - redis
    networks:
      - mail_network
      - reverseproxy
```
