### ISSUE TITLE
Can spoof inbound mail on local network 

### ISSUE THREAD

**Issue by YoloClin** [hardware/mailserver#405]
#### Classification

* [X] Question

#### Reproducibility

* [X] Always

#### Docker information
``` docker info
Containers: 4
 Running: 4
 Paused: 0
 Stopped: 0
Images: 4
Server Version: 18.09.7
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 
runc version: N/A
init version: v0.18.0 (expected: fec3683b971d9c3ef73f284f176672c44b448662)
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-58-generic
Operating System: Ubuntu 18.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 985.5MiB
Name: mail
ID: GJNY:4YWL:KHXA:QAHB:FRZR:3H6N:5ZVS:R3XC:5SE7:EU5X:RELW:GOLD
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
root@mail:~/mailserver# docker images hardware/mailserver --digests --filter "dangling=false"
REPOSITORY            TAG                 DIGEST                                                                    IMAGE ID            CREATED             SIZE
hardware/mailserver   1.1-stable          sha256:4875f76004ef9976099bd12e1f16671776d7d20f788d59cc279a17d63add73ac   c4513232af37        12 days ago         375MB
```

#### Description
I can spoof email when communicating with the mailserver on local network addresses (both 127.0.0.1 _and_ 10.0.0.0/x network addresses work, for reference my mailserver and host are on 10.x  network with a /24 subnet, with both hosts in the same subnet)

#### Steps to reproduce

```python
import smtplib
import socket

def self_spoof():
    fromaddr = "hacker@gmail.com"
    toaddrs  = ["victim@mydomain", ]
    msg = ("From: %s\r\nSubject: HelloWorld\r\nTo: %s\r\n\r\n"
           % (fromaddr, ", ".join(toaddrs)))
    msg += "Hello World"
    server = smtplib.SMTP("localhost")
    server.starttls()
    server.set_debuglevel(1)
    server.sendmail(fromaddr, toaddrs, msg)
    server.quit()
self_spoof()
```
1.  replace `toaddrs` with a valid email which is hosted by the mailserver on localhost
2. Optionally replace `localhost` with the local IP of the system and run from an adjacent host on the same network 
3.  `python3 spoof.py`
4. The email will not be marked as spam

In contrast, replace `localhost` with the FQDN, the email will be marked as spam

#### Expected results
Email should be flagged as spam, the same email with the hosts' FQDN receives a spam score of 9.49/15.

```
X-Spamd-Result: default: False [9.49 / 15.00];
	 ARC_NA(0.00)[];
	 GREYLIST(0.00)[pass,body];
	 MIME_TRACE(0.00)[0:+];
	 FREEMAIL_FROM(0.00)[gmail.com];
	 MISSING_DATE(1.00)[];
	 MIME_GOOD(-0.10)[text/plain];
	 TO_DN_NONE(0.00)[];
	 R_SPF_SOFTFAIL(0.00)[~all:c];
	 RCPT_COUNT_ONE(0.00)[1];
	 IP_SCORE_FREEMAIL(0.00)[];
	 MISSING_MID(2.50)[];
	 TO_MATCH_ENVRCPT_ALL(0.00)[];
	 MX_GOOD(-0.01)[cached: alt3.gmail-smtp-in.l.google.com];
	 FROM_NO_DN(0.00)[];
	 IP_SCORE(0.00)[country: US(-0.01)];
	 VIOLATED_DIRECT_SPF(3.50)[];
	 RCVD_COUNT_ZERO(0.00)[0];
	 FROM_EQ_ENVFROM(0.00)[];
	 R_DKIM_NA(0.00)[];
	 FREEMAIL_ENVFROM(0.00)[gmail.com];
	 ASN(0.00)[asn:14061, ipnet:134.209.48.0/20, country:US];
	 TAGGED_FROM(0.00)[];
	 HFILTER_HOSTNAME_UNKNOWN(2.50)[];
	 DMARC_POLICY_SOFTFAIL(0.10)[gmail.com : No valid SPF, No valid DKIM,none]
```

#### Actual results
Email is not marked as spam, it receives a score of 3.40/15

```
X-Spamd-Result: default: False [3.40 / 15.00];
	 ARC_NA(0.00)[];
	 FREEMAIL_FROM(0.00)[gmail.com];
	 MISSING_DATE(1.00)[];
	 MIME_GOOD(-0.10)[text/plain];
	 TO_DN_NONE(0.00)[];
	 RCPT_COUNT_ONE(0.00)[1];
	 MISSING_MID(2.50)[];
	 TO_MATCH_ENVRCPT_ALL(0.00)[];
	 FROM_NO_DN(0.00)[];
	 RCVD_COUNT_ZERO(0.00)[0];
	 FROM_EQ_ENVFROM(0.00)[];
	 MIME_TRACE(0.00)[0:+];
	 FREEMAIL_ENVFROM(0.00)[gmail.com]
```

I'm unsure if this is expected behaviour, I wouldn't care if it were limited to localhost, but a host on the same subnet is also able to reliably spoof email. 

#### Debugging information
```
docker logs mailserver
```

#### Configuration (docker-compose.yml, traefik.toml...etc)

```
services:
  mailserver:
    image: hardware/mailserver:${MAILSERVER_DOCKER_TAG}
    restart: ${RESTART_MODE}
    domainname: ${MAILSERVER_DOMAIN}
    hostname: ${MAILSERVER_HOSTNAME}
    ports:
      - "25:25"         
      - "143:143"       
      - "587:587"       
      - "127.0.0.1:11334:11334"
    environment:
      - DBPASS=${DATABASE_USER_PASSWORD}
      - RSPAMD_PASSWORD=${RSPAMD_PASSWORD}
      - DISABLE_CLAMAV=true
      - PASSWORD_SCHEME=PLAIN 
    volumes:
      - ${VOLUMES_ROOT_PATH}/mail:/var/mail
    depends_on:
      - mariadb
      - redis
    networks:
      - mail_network
      - http_network
```
