### ISSUE TITLE
Invalid query: Table 'postfix.config' doesn't exist

### ISSUE THREAD

**Issue by Vingtoft** [hardware/mailserver#47]
I'm hosting the mailserver on an instance on AWS. 
I've had to upgrade the instance, so I created a new image based on the mailserver instance. 
After upgrading and running `docker-compose up`, the following error is printed out when pointing the browser to postfixadmin.mydomain.com: 

`Invalid query: Table 'postfix.config' doesn't exist`

Im a little confused about this error, because all the files (including the databases) is present on the new instance .

Any idea of why this bug is present and how to fix it?

**Comment by Vingtoft** [comment]
It turns out its required to complete the entire postfix setup process. Is there any way to keep postfix settings after a docker rebuild?

**Comment by vizv** [comment]
Did you mount those two volume to enable data persistency? `/var/mail` and `/etc/opendkim/keys`

**Comment by Vingtoft** [comment]
I mounted the two volumes on the mailserver container (build from hardware/mailserver image), but not mounted the two volumes on postfix container. Perhaps thats the problem? 

docker-compose (simplified a bit):

```
mailserver:
  image: hardware/mailserver
  container_name: mailserver
  domainname: modusanitas.com
  hostname: mail
  links:
    - mariadb:mariadb
  ports:
    - "25:25"     # SMTP                - Required
    - "143:143"   # IMAP       STARTTLS - For webmails/desktop clients
    - "465:465"   # SMTPS      SSL/TLS  - Enabled for compatibility reason, otherwise disabled
    - "587:587"   # Submission STARTTLS - For webmails/desktop clients
    - "993:993"   # IMAPS      SSL/TLS  - For webmails/desktop clients
    - "4190:4190" # SIEVE      STARTTLS - Optional, but recommended for mail filtering
  environment:
    - DBPASS=xxxxxxx
  volumes:
    - ./mail:/var/mail
    - ./opendkim:/etc/opendkim/keys

# Control panel
postfixadmin:
  image: hardware/postfixadmin
  container_name: postfixadmin
  domainname: modusanitas.com
  hostname: mail
  links:
    - mailserver:mailserver
    - mariadb:mariadb
  environment:
    - DBPASS=xxxxxxx
```
