### ISSUE TITLE
Rancher catalog integration

### ISSUE THREAD

**Issue by maZahaca** [hardware/mailserver#83]
Sorry for disturbing you ;)

Have you ever tried rancher.com orchestration tool?
It's one of the modern and updatable tool ever (and it's FREE)

They also provide ability to run services from `docker-compose.yml`
I just have configured infrastructure on it, and going to use your mail server. Would be good to share experience and improve you repo.

**Comment by hardware** [comment]
I don't use Rancher, but why not. The best thing to do is to try it out :)

**Comment by maZahaca** [comment]
I'm trying it now.
@hardware 
Is it possible somehow use env variable to pass special things to setup tool instead of going to setup.php and doing stuff.

It would be just perfect, when you start container for the first time it warmups env: create dirs, configures db and everything what is needed.

**Comment by hardware** [comment]
Postfixadmin installation require user to launch the installer and postfix database require manual setup by entering domain name, quotas, mailboxes...etc I can not automate everything. It could be a bit tricky.

**Comment by AndreSteenbergen** [comment]
With the FQDN and Domain environment settings everything works as a charm.

I am only struggling with the rDNS settings as reported by mail-tester.com. I guess I need to read up on that ... I need to set some PTR record.

**Comment by AndreSteenbergen** [comment]
Here is my docker compose file:

```
version: '2'
volumes:
  mail-server-rainloop:
    external: true
    driver: 'null'
  mail-server:
    external: true
    driver: 'null'
  mail-server-redisdb:
    external: true
    driver: 'null'
  mail-server-mariadb:
    external: true
    driver: 'null'
services:
  mariadb:
    image: mariadb:10.2
    environment:
      MYSQL_ROOT_PASSWORD: XXXXXXXXXXXXX
      MYSQL_DATABASE: postfix
      MYSQL_USER: postfix
      MYSQL_PASSWORD: XXXXXXXXXXXXX
    stdin_open: true
    volumes:
    - mail-server-mariadb:/var/lib/mysql
    tty: true
    labels:
      io.rancher.container.pull_image: always
  rainloop:
    image: hardware/rainloop
    stdin_open: true
    volumes:
    - mail-server-rainloop:/rainloop/data
    tty: true
    links:
    - mariadb:mariadb
    - mailserver:mailserver
    labels:
      rap.port: '8888'
      rap.le_host: webmail.claxe.com
      io.rancher.container.pull_image: always
      rap.host: webmail.claxe.com
  postfixadmin:
    image: hardware/postfixadmin
    hostname: mail
    environment:
      DBPASS: XXXXXXXXXXXXXXXXXX
    stdin_open: true
    domainname: claxe.com
    tty: true
    links:
    - mariadb:mariadb
    - mailserver:mailserver
    labels:
      rap.port: '8888'
      rap.le_host: postfixadmin.claxe.com
      io.rancher.container.pull_image: always
      rap.host: postfixadmin.claxe.com
  mailserver:
    image: hardware/mailserver:1.1-stable
    environment:
      DBPASS: XXXXXXXXXXXXXXXXXXX
      RSPAMD_PASSWORD: XXXXXXXXXXXXXXXXXX
      FQDN: mail.claxe.com
      DOMAIN: claxe.com
      ADD_DOMAINS: claxe.nl
    stdin_open: true
    volumes:
    - mail-server:/var/mail
    tty: true
    links:
    - mariadb:mariadb
    - redis:redis
    ports:
    - 25:25/tcp
    - 143:143/tcp
    - 587:587/tcp
    - 993:993/tcp
    - 4190:4190/tcp
    labels:
      io.rancher.container.pull_image: always
  redis:
    image: redis:4.0-alpine
    stdin_open: true
    volumes:
    - mail-server-redisdb:/data
    tty: true
    command:
    - redis-server
    - --appendonly
    - 'yes'
    labels:
      io.rancher.container.pull_image: always
```
